<html>
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body >
	<div class="contenedor" style="width: 420px;
			border:2px solid #05AADD;
			padding:2em;
			margin:0 auto;
			font-size: 12px;
			font-family: 'Arial';">
		<div class="div-img" style="text-align: center;">
			<img src="http://dev.epass.clickslatam.com/static/img/logo.svg" class="img" style="width: 100px">
		</div>
		<div class="body-mensaje" style="padding:1em;">
			<div class="bienvenido">
				<h3 style="color:#333333">Bienvenido <span class="email-mensaje" style="text-decoration: none">jhonsmith@hotmail.com</span>,</h3>
			</div>
			<div class="descripcion-cuerpo" style="font-size: 1.1em;
    			line-height: 1.7em;
    			color: #3C3B3B;">
				<p>
					Estas muy cerca de obtener tu cuenta de usuario web en e-pass. Sólo falta que actives tu cuenta y para eso sólo necesitas hacer click en el siguiente enlace:
				</p>
				<a class="confirmar" style="" href="color:#05AADD;
			text-decoration: underline">Aquí Confirma tu Registro</a>
				<p>
					Luego de realizar la activación de la cuenta, podrás iniciar la sesión con tu correo electrónico y contraseña que ingresaste en tu registro.
				</p>
				<p>
					Recuerda que este enlace de 'Confirmación de Cuenta' que se te ha proporcionado estará activo dentro de las 24 horas luego de haberte registrado de lo contrario tendrás que solicitar nuevamente la activación de tu cuenta.
				</p>
	
				<p>	Para preservar la seguridad de tu cuenta, no reenvíes este mensaje a nadie. </p>
​
				<p>	Atentamente,<br>
					El equipo de e-pass
				</p>
			</div>
		</div>
	</div>
	
</body>
</html>