<html>
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body >
	<div class="contenedor" style="width: 420px;
			border:2px solid #05AADD;
			padding:2em;
			margin:0 auto;
			font-size: 12px;
			font-family: 'Arial';">
		<div class="div-img" style="text-align: center;">
			<img src="http://dev.epass.clickslatam.com/static/img/logo.svg" class="img" style="width: 100px">
		</div>
		<div class="body-mensaje" style="padding:1em;">
			<div class="bienvenido">
				<h3 style="color:#333333">Bienvenido <span class="email-mensaje" style="text-decoration: none">jhonsmith@hotmail.com</span>,</h3>
			</div>
			<div class="descripcion-cuerpo" style="font-size: 1.1em;
    			line-height: 1.7em;
    			color: #3C3B3B;">
				<p>	
					Ya eres parte de e-pass. Ahora podrás realizar las siguientes operaciones con tu cuenta de usuario web en e-pass:
				</p>
				<ul>
					<li>Ver tus saldos</li>
					<li>Recargar tus planes</li>
					<li>Modificar tus Datos Personales</li>
					<li>Obtener tus últimos Reportes (Movimientos y Transacciones)</li>
					<li>Acceder a tus Comprobantes de Pago</li>
					<li>Acceder a tus vehículos</li>
				</ul>

				<p>	Atentamente,<br>
					El equipo de e-pass
				</p>
			</div>
		</div>
	</div>
	
</body>
</html>