<style >
		td{

		margin: 15px;
  		padding: 8px;	
		}
	</style>
		<div class="contenedor" style="width: 500px;
			border:2px solid #05AADD;
			padding:2em;
			margin:0 auto;
			font-size: 12px;
			font-family: 'Arial';
			color:#333333">
		<div class="div-img" style="text-align: center;">
			<img src="http://dev.epass.clickslatam.com/static/img/logo.svg" class="img" style="width: 100px">
		</div>
		<div class="body-mensaje" style="padding:1em;">
			<div class="bienvenido">
				<h3 style="color:#333333">Estimado Cliente </h3>
			</div>
			<div class="descripcion-cuerpo" style="font-size: 1.1em;
    			line-height: 1.7em;
    			color: #3C3B3B;">
				<p>	
					Muchas gracias por afiliarte al Plan <span>Pre-Pago </span>en e-pass Te brindamos los datos del proceso de afiliación que has realizado.
				</p>
				<table border="1" style="border-collapse: collapse;width: 100%;font-size: 14px;margin-bottom: 10px;line-height: 20px;">
					<thead style="background: #05AADD;color: white;">
						<th colspan="4" style="text-align: center ">Datos del Plan</th>
					</thead>
					<tbody>
						<tr>
							<td style="font-weight: bold">Plan</td>
							<td>Individual</td>
							<td style="font-weight: bold">Monto</td>
							<td >50.00</td>
						</tr>
						<tr>
							<td style="font-weight: bold">Numero de Contrato</td>
							<td>012478547</td>
							<td style="font-weight: bold">Numero de Transacción</td>
							<td >01247847</td>
						</tr>
						<tr>
							<td style="font-weight: bold">Tipo de Pago</td>
							<td>Visa</td>
							<td style="font-weight: bold">Fecha</td>
							<td >08/03/2016</td>
						</tr>
					</tbody>
				</table>
				
				<table border="1" style="border-collapse: collapse;width: 100%;font-size: 14px;margin-bottom: 50px;line-height: 20px;">
					<thead style="background: #05AADD;color: white;">
						<th colspan="4" style="text-align: center ">Datos del Cliente</th>
					</thead>
					<tbody>
						<tr>
							<td style="font-weight: bold">Nombre y Apellidos</td>
							<td>Jhon Smith Taylor</td>
						</tr>
						<tr>
							<td style="font-weight: bold">Tipo de Documento</td>
							<td>DNI</td>
						</tr>
						<tr>
							<td style="font-weight: bold">Número</td>
							<td>08747847</td>
						</tr>
					</tbody>
				</table>
				<p style="font-size: 10px;padding-top: 10px;border-top: 3px solid gray;">	Este correo fue enviado de manera automática. Si no realizaste esta operación por favor envíanos un mensaje a atencionalcliente@epass.pes
				</p>
			</div>
		</div>
	</div>