        <style type="text/css">
        .contenedor {
            margin: 0; padding: 0; min-width: 98%!important;
                     width: 98%; max-width: 700px;
        }

        </style>
        <BODY
	<div class="contenedor" style="
			border:2px solid #05AADD;
			padding:5px;
			margin:0 auto;
			font-size: 12px;
			font-family: 'Arial';
                        min-width: 98%!important;
                        width: 98%; 
                        max-width: 700px;
                        ">
                <div class="div-img" style="text-align: center;">
                     <img src="http://local.epass.com/static/img/mail-header-bienvenida.jpg" class="img" style="width: 100%">
                 </div>
		<div class="body-mensaje" style="padding:1em;text-align: center;">
			<div class="bienvenido">
				<h3 style="color:#009ddf;font-size: 17px;">Hola <span class="email-mensaje" style="font-style: italic;text-decoration: none; color: #f08b00; font-size: 17px;">jhonsmith@hotmail.com</span></h3>
			</div>
			<div class="descripcion-cuerpo" style="font-size: 1.1em;
    			line-height: 16px;
    			color: #009ddf;">
                           
                    
				<p>
                                    <strong>Bienvenid@</strong> <span style="font-style: italic;">a nuestro nuevo portal web e-pass, <br>
Haz click aqui y disfruta de los nuevos beneficios.</span>
				</p>

			</div>
                        <div class="div-img" style="text-align: center; margin-bottom: 25px; margin-top: 25px">
                            <a href="#"><img src="http://local.epass.com/static/img/mail-bienvenido-boton.png" class="img" style="width: 200px"></a>
                        </div>
                        <div class="div-img" style="text-align: center; ">
                            <img src="http://local.epass.com/static/img/mail-bienvenido-icons.png" class="img" style="width: 380px">
                        </div>
                    <table>
                        <tr>
                            <td>
                                    <div style="
                                            width: 150px;
                                            text-align: left;
                                            color: #fff;
                                            padding: 10px;
                                            font-size: 10px;
                                            padding-right: 15px;
                                            line-height: 11px;
                                            background-color: #009ddf;
                                            border-top-right-radius: 118px;
                                    ">
                                        <div style="font-size: 8px;">Linea de Atención al Cliente</div>


                                            <div style="    font-size: 12px;
                                                padding-bottom: 3px;
                                                padding-top: 3px;
                                                display: inline-block;
                                            ">
                                                0800-45045 <br>
                                                249-7222
                                            </div>

                                                <br>
                                            <div style="font-size:7px; padding-bottom: 3px; display: inline-block;"> 
                                                Para cualquier consulta adicional no dude en escribirnos a atencionalcliente@epass.pe
                                            </div>
                                            <br>
                                            <div style=""><strong>www.epass.pe</strong></div>

                                    </div> 
                            </td>
                            <td align="right" valign="bottom" style="color: #009ddf; font-size: 10px; padding-bottom: 15px;" >
                                <img src="http://local.epass.com/static/img/mail-rows-orange.png" class="img" style="width: 50px"><br>
                                Para preservar la seguridad de tu cuenta, no reenvíes este mensaje,<br>
este enlace sólo estará activo por 24 horas.
                            </td>
                        </tr>
                    </table>

		</div>
	</div>