
        <style type="text/css">
        .contenedor {
            margin: 0; padding: 0; min-width: 100%!important;
                     width: 100%; max-width: 700px;
        }

        </style>
	<div class="contenedor" style="
			border:2px solid #05AADD;
			padding:5px;
			margin:0 auto;
			font-size: 12px;
			font-family: 'Arial';">
                <div class="div-img" style="text-align: center;">
                     <img src="http://local.epass.com/static/img/mail-header.jpg" class="img" style="width: 100%">
                 </div>
		<div class="body-mensaje" style="padding:1em;">
			<div class="bienvenido">
				<h3 style="color:#009ddf;font-size: 17px;">Bienvenid@ <span class="email-mensaje" style="font-style: italic; text-decoration: none; color: #f08b00; font-size: 17px;">jhonsmith@hotmail.com</span></h3>
			</div>
			<div class="descripcion-cuerpo" style="font-size: 1.1em;
    			line-height: 13px;
    			color: #009ddf;">
                           
                                <table style="color: #009ddf; font-size: 13px;">
                                    <tr >
                                        <td valign="top" width="30" ><img src="http://local.epass.com/static/img/mail-item.png" class="img" style="width: 30px"> </td>
                                        <td style="padding-bottom: 10px"> Con la Activación de tu Cuenta podrás ver tus saldos, tus consumos y recargar fácil y rápido.
                                        </td>
                                    </tr>  
                                <tr>
                                        <td valign="top" width="30"><img src="http://local.epass.com/static/img/mail-item.png" class="img" style="width: 30px"> </td>
                                        <td> Luego de Activar tu Cuenta, podrás Iniciar la Sesión utilizando tu correo electrónico y la contraseña que ingresaste al momento de registrarte en la web.
                                        </td>
                                    </tr>  
                                </table>				
                                    
			</div>
                        <div class="div-img" style="text-align: center; margin-bottom: 25px; margin-top: 25px">
                            <a href="#"><img src="http://local.epass.com/static/img/mail-activar-boton.png" class="img" style="width: 200px"></a>
                        </div>
		</div>
                <div class="div-img" style="text-align: center;">
                    <img src="http://local.epass.com/static/img/mail-footer2.png" class="img" style="width: 100%">
                </div>
	</div>