<html>
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body >
	<div class="contenedor" style="width: 440px;
			border:2px solid #05AADD;
			padding:2em;
			margin:0 auto;
			font-size: 12px;
			font-family: 'Arial';">
		<div class="div-img" style="text-align: center;">
			<img src="http://dev.epass.clickslatam.com/static/img/logo.svg" class="img" style="width: 100px">
		</div>
		<div class="body-mensaje" style="padding:1em;">
			<div class="bienvenido">
				<h3 style="color:#333333">Hola <span class="email-mensaje" style="text-decoration: none">jhonsmith@hotmail.com</span>,</h3>
			</div>
			<div class="descripcion-cuerpo" style="font-size: 1.1em;
    			line-height: 1.7em;
    			color: #3C3B3B;">
				<p>	
					Recientemente has solicitado la recuperación de la contraseña de tu cuenta de usuario web en e-pass. Para completar el proceso, haz click en el siguiente enlace:
				</p>
				<a class="confirmar" style="" href="color:#05AADD;
			text-decoration: underline">Aquí Restablecer tu Contraseña</a>

				<p>
					Si no solicitaste el cambio de contraseña puedes hacer caso omiso a este mensaje o escríbenos a atencionalcliente@epass.pe
				</p>
				<p>
					Para preservar la seguridad de tu cuenta, no reenvíes este mensaje a nadie. 
				</p>
				<p>	Te informamos que este enlace sólo estará activo por 24 horas desde la fecha de solicitud. 
				</p>

				<p>	Atentamente,<br>
					El equipo de e-pass
				</p>
			</div>
		</div>
	</div>
	
</body>
</html>