<html>
    <head>
        <meta charset="UTF-8">
        <title>Mensaje de Contact&aacute;nos</title>
    </head>
    <body>
        <div class="contenedor" style="width: 420px;border:2px solid #05AADD;padding:2em;
             margin:0 auto;font-size: 12px;font-family: 'Arial';">
            <div class="div-img" style="text-align: center;">
                <img src="<?=$this->view->linkCdn('/img/epass.png');?>" class="img" style="width: 100px">
            </div>
            <div class="body-mensaje" style="padding:1em;">
                <div class="bienvenido">
                    <h3 style="color:#333333">Hola administrador <span class="email-mensaje" style="text-decoration: none"><?php echo (is_array($this->mailAdmin))?implode(', ',$this->mailAdmin):$this->mailAdmin; ?></span>,</h3>
                </div>
                <div class="descripcion-cuerpo" style="font-size: 1.1em;line-height: 1.7em;color: #3C3B3B;">
                    <p>
                        El usuario <?php echo $this->nombre; ?> le env&iacute;o el siguiente mensaje desde la opci&oacute;n Cont&aacute;ctanos del web site de epass.
                    </p>
                    <p>Asunto: <?php echo $this->asunto; ?></p>
                    <p>Mensaje: <?php echo $this->mensaje; ?></p>
                    <p>Datos del usuario:</p>
                    <ul>
                        <li>Nombre: <?php echo $this->nombre; ?></li>
                        <li>Tel&eacute;fono: <?php echo $this->telefono1; ?></li>
                        <li>Tel&eacute;fono Adicional: <?php echo $this->telefono2; ?></li>
                        <li>Correo: <?php echo $this->correo; ?></li>
                    </ul>
                    <p>Atentamente,<br>El equipo de e-pass</p>
                </div>
            </div>
        </div>
    </body>
</html>