         <style type="text/css">
        .contenedor {
            margin: 0; padding: 0; 
                     width: 100%; 
        }
        a,a:link{
            color: #fff;
        }
        body
        {
            padding: 0;
            margin: 0;
            font-size: 16px;
        }
        </style>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <div class="contenedor" style="
            
            margin:0 auto;
            font-size: 12px;
            font-family: 'Arial';">
                <div class="div-img" style="text-align: center;">
                    <div style="float:left;width: 49%;text-align: center;margin-top: 4%;">
                        <img src="<?=$this->view->linkCdn('/img/logo.jpg');?>"  class="img" style="width: 70%;">
                    </div>
                     <div style="float:right;width: 49%;text-align: right;">
                         <img src="<?=$this->view->linkCdn('/img/arrow_email_header.jpg');?>"  class="img" style="width: 57%;">
                     </div>
                 </div>
        <div class="body-mensaje" style="clear:both;font-family: 'Open Sans', sans-serif;text-align: center;">
            <div class="bienvenido">
                <h3 style="color:#009ddf;font-size: 17px;">
                    <span style="color: #009ddf;
                        font-size: 1.4em;
                        font-weight: bold;
                        font-style: italic;">Hola</span> 
                    <span class="email-mensaje" style="font-style: italic;text-decoration: none; color: #f08b00; font-size: 17px;"><?php echo $this->name; ?></span></h3>
            </div>
            <div class="descripcion-cuerpo" style="
                font-size: 1.5em;
                /* line-height: 22px; */
                color: #009ddf;
                /* font-weight: bold; */
                ">
                           
                    
                <p>
                                    <strong style="color: #009ddf;">Bienvenid@</strong> 
                                    <span style="color: #009ddf;">a nuestro nuevo portal web e-pass,</span> <br>
                                    <span style="font-style: italic;">Haz click aquí y disfruta de los nuevos beneficios.</span>
                </p>

            </div>
                        <div class="div-img" style="text-align: center; margin-bottom: 25px; margin-top: 25px">
                            <a href="<?php echo $this->url?>">

                            <img src="<?=$this->view->linkCdn('/img/nueva_web.jpg');?>"  class="img" style="width: 38%"></a>
                        </div>
                        <div class="div-img" style="text-align: center;margin-bottom: 3em; ">
                            <img src="<?=$this->view->linkCdn('/img/nuevo_comodo_simple_email.jpg');?>" class="img" style="width: 70%;">
                        </div>
                        <div style="">
                            <div style="float: left;width: 40%;">
                                <img src="<?=$this->view->linkCdn('/img/fot_img.jpg');?>" style="width: 100%;"  class="img" > 
                            </div>
                            <div style="float: right;
                                    width: 60%;
                                    margin-top: 8%;
                                    text-align: right;">                         
                                        <img src="<?=$this->view->linkCdn('/img/preservar_mensaje.jpg');?>"  style="width: 100%;">                             
                            </div>
                        </div>
                                
                           
                            
                                
                            

        </div>
    </div>      


