<?php   $this->headLink()
    ->prependStylesheet($this->linkCdn('/css/persona/persona.css'))
?>
<?php  $this->inlineScript()
    ->prependFile($this->linkCdn('/js/persona/persona.js'))
; ?>


<!--**************Conoce Nuestro Plan Individual **************-->
<div class=" contenedor-gotas-personas">
    <div class="col-xs-12 col-sm-1 col-md-1">
    </div>
    <div class="col-xs-12 col-sm-5 col-md-5">
        <!--************** gota ePass **************//-->
        <div class="gota-epas bg-celeste bg-celeste-woman" href="#planes_individual">
          <div class="gota-epas-titulo"><span>Individual</span></div>
          <div class="gota-epas-img gota-epas-img-transarent-celeste">
            <div class="gota-epas-btn"><a id="href_planes_individuales" ><span>Ver Paquetes</span><i class="fa fa-angle-right"></i></a></div>
          </div>
        </div>
        <!--************** gota ePass **************//-->
        
    </div>
    <div class="col-xs-12 col-sm-5 col-md-5 ">
        <!--************** gota ePass **************//-->
        <div class="gota-epas bg-green gota-persona-familia" href="#planes_familiares">
          <div class="gota-epas-titulo"><span>Compartida</span></div>
          <div class="gota-epas-img gota-epas-img-transarent-green">
            <div class="gota-epas-btn"><a id="href_planes_familiares" ><span>Ver Paquetes</span><i class="fa fa-angle-right"></i></a></div>
          </div>
        </div>
        <!--************** gota ePass **************//-->
    </div>
    <div class="col-xs-12 col-sm-1 col-md-1">
    </div>
</div>
<div class="titleEnPersona" id="planes_individual">
    Paquetes de Recarga de la Cuenta Individual
</div>

<!-- slider-paquetes-individuales -->
<div class="col-md-12 sinPaddingRight">
    <div class="hidden-xs col-sm-1 col-md-1 margencito txtalgnright_flecha_prev">
        <a class="btn prevRecargaInd">
            <i class="fa fa-angle-left flechaSlider flechaSlider-left"></i>
        </a>
    </div>
    <div class="col-xs-12 col-sm-10 col-md-10">
        <div id="demo">
            <div class="row">
                <div class="span12">
                    <div id="recarga-individual" class="owl-carousel">
                         <?php foreach($this->paquetes['individual'] as $index => $paquete){ ?>
                            <div class="item">
                                <div class="paqueteEpass">

                                    <div class="paqueteEpass-Titulo bgceleste">
                                        <span>Paquete <?= ($index + 1) ?></span>
                                    </div>

                                    <div class="contenedorContenido borderCeleste">
                                        <div class="paqueteEpass-Contenido">
                                            <div class="paqueteEpass-Contenido-Precio bgceleste"><span class="soles">S/.</span>
                                                <div class="precio"><span><?= number_format($paquete->total, 2) ?> </span><span> *</span></div>
                                            </div>
                                            <div class="paqueteEpass-Contenido-Recarga"><span class="colorceleste">Solo Recarga</span></div>
                                            <div class="paqueteEpass-Contenido-bloque1 dashedCeleste">
                                                <span>Tasa Recarga</span>
                                                <span class="saldo-monto">S/. <?= number_format($paquete->tasaRecarga, 2) ?></span>
                                            </div>

                                            <div class="paqueteEpass-Contenido-bloque3 sinDashed">
                                                <span >Saldo para Uso</span>
                                                <span class="saldo-monto"> S/.<?= number_format($paquete->saldoUso, 2) ?></span>
                                            </div>
                                            <div class="paqueteEpass-Contenido-VerMas bgCelesteTransparent">
                    
                                                    <span class="bgceleste" onclick="recargaEvent()">Recarga</span></div>
                              
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php }?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="hidden-xs col-sm-1 col-md-1 margencito">
        <a class="btn nextRecargaInd">
            <i class="fa fa-angle-right flechaSlider flechaSlider-right"></i>
        </a> 
    </div>
</div>
<!-- ./slider-paquetes-individuales -->

<div class="dashedLine"></div>

<div class="titleEnPersona" id="planes_familiares">
    Paquetes de Recarga de la Cuenta Compartida
</div>

<!-- slider-paquetes-familiares -->
<div class="col-md-12 sinPaddingRight">
    <div class="hidden-xs col-sm-1 col-md-1 margencito txtalgnright_flecha_prev">
        <a class="btn prevRecargaFam">
            <i class="fa fa-angle-left flechaSlider flechaSlider-left span-color-green"></i>
        </a>
    </div>
    <div class="col-xs-12 col-sm-10 col-md-10">
        <!--************** slider touch **************//-->
        <div id="demo">
            <div class="row">
                <div class="span12">
                    <div id="recarga-familiar" class="owl-carousel">
                        <?php foreach($this->paquetes['familiar'] as $index => $paquete){?>
                            <div class="item">
                                <div class="paqueteEpass">
                                    <div class="paqueteEpass-Titulo pack-epass-bggreen">
                                        <span>Paquete <?= ($index + 1) ?></span>
                                    </div>
                                    <div class="contenedorContenido pack-epass-bordergreen">
                                        <div class="paqueteEpass-Contenido">
                                            <div class="paqueteEpass-Contenido-Precio pack-epass-bggreen"><span class="soles">S/.</span>
                                                <div class="precio"><span><?= number_format($paquete->total, 2) ?> </span><span> *</span></div>
                                            </div>
                                            <div class="paqueteEpass-Contenido-Recarga span-color-green"><span>Solo Recarga</span></div>
                                            <div class="paqueteEpass-Contenido-bloque1 dashed-green">
                                                <span>Tasa Recarga</span><span class="saldo-monto">S/. <?= number_format($paquete->tasaRecarga, 2) ?></span>
                                            </div>
                                            <div class="paqueteEpass-Contenido-bloque3 sinDashed">
                                                <span>Saldo para Uso</span><span class="saldo-monto"> S/. <?= number_format($paquete->saldoUso, 2) ?></span>
                                            </div>

                                            <div class="paqueteEpass-Contenido-VerMas border-green-rgba bg-green-rgba">
                                                        <span class="pack-epass-bggreen" onclick="recargaEvent()">Recarga</span>
                          
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php }?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="hidden-xs col-sm-1 col-md-1 margencito">
        <a class="btn nextRecargaFam">
            <i class="fa fa-angle-right flechaSlider flechaSlider-right span-color-green"></i>
        </a> 
    </div>
</div>
<!-- ./slider-paquetes-familiares -->
</div>
<div class="texto-asterisco">
    (*) El costo del TAG por vehículo afiliado al contrato será adicionado al monto del paquete elegido y el mismo será cobrado al concluir su afiliación
</div>
<div class="row col-md-12 publicidadEpass" >
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="publicidadEpass-Texto">Si no cuentas con el TAG de <i class=italic>e-pass</i>, ¡Qué esperas!</div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 center">
        <div class="publicidadEpass-Button">
        <a href="<?php echo $this->url('personas') ?>">
            <span>Afiliate Aquí</span>
            <i class="fa fa-angle-right"></i>
        </a>
        </div>
    </div>
</div>
