<div>
  <h3>Formulario para visa</h3>
<form method="post" action="<?php echo $this->action;?>">
  <input type="hidden" name="ETICKET" value="<?php echo $this->eticket;?>"/>
  <input type="submit" value="Enviar a Visa"/>
</form>
</div>
<div>
  <h3>Formulario para amex</h3>
<form method="post" name="frm" action="<?php echo $this->amex;?>">
  <?php
    $i=0;
    foreach ($this->datos as $dato) {?>
      <input type="hidden" name="<?php echo "I".($i+1); ?>" value="<?php echo $dato;?>"/>
    <?php
    $i++;
  }
   ?>
  <input name="enviar amex" type="submit" value="Enviar a amex"/>
</form>
</div>
