<?php

namespace ZfSimpleMigrations\Migrations;

use ZfSimpleMigrations\Library\AbstractMigration;
use Zend\Db\Metadata\MetadataInterface;

class Version20160321123651 extends AbstractMigration
{
    public static $description = "Table ePass.APLAZA";
    public static $author = "Renzo Tejada";

    public function up(MetadataInterface $schema)
    {
        $this->addSql("
            CREATE TABLE aplaza (
                TOLLCOMPANY varchar(2) NOT NULL,
                PLAZA varchar(2) NOT NULL,
                PLAZANODE varchar(4) NOT NULL,
                LANENODE varchar(9) NOT NULL,
                NAME varchar(64) NOT NULL,
                TIMEREVOK varchar(14) DEFAULT NULL,
                DAYCLOSED varchar(8) DEFAULT NULL,
                ROAD varchar(20) DEFAULT NULL,
                KM varchar(20) DEFAULT NULL,
                ADDRESS varchar(100) DEFAULT NULL,
                MINSTOCK INT(5) NOT NULL DEFAULT 0 ,
                PRIMARY KEY (`TOLLCOMPANY`,`PLAZA`)
            ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','01','0000','LOCALSERV','Chillón','19700102000000','19700101','Panamericana Norte','25','Car. Autopista Panamericana Norte KM 25 - Puente Piedra - Lima ',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','02','0000','LOCALSERV','Huaylas',NULL,NULL,NULL,NULL,NULL,0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','03','0000','LOCALSERV','Villa','19700102000000','19700101','Panamericana Sur','19.8','Car. Autopista Panamericana Sur KM 19.8 - Villa el Salvador - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','04','0000','LOCALSERV','Conchán','19700102000000','19700101','Panamericana Sur','25','Car. Autopista Panamericana Sur KM 25.5 - Lurín - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','05','0000','LOCALSERV','San Pedro','19700102000000','19700101','Panamericana Sur','31','Car. Autopista Panamericana Sur KM 31.1 - Lurín - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','06','0000','LOCALSERV','Quebrada Seca','19700102000000','19700101','Panamericana Sur','42','Car. Autopista Panamericana Sur KM 42 - Punta Hermosa  - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','07','0000','LOCALSERV','Arica','19700102000000','19700101','Panamericana Sur','35','Car. Autopista Panamericana Sur KM 35 - Lurín - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','09','0000','LOCALSERV','Punta Negra','19700102000000','19700101','Panamericana Sur','45.1','Car. Autopista Panamericana Sur KM 45.1 - Punta Negra - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','50','0000','LOCALSERV','Acceso San Pedro','19700102000000','19700101','Panamericana Sur','31','Car. Autopista Panamericana Sur KM 31 - Lurín - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','70','0000','LOCALSERV','Acceso Arica','19700102000000','19700101','Panamericana Sur','36','Car. Autopista Panamericana Sur KM 36 - Lurín - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '01','90','0000','LOCALSERV','Acceso Punta Negra','19700102000000','19700101','Panamericana Sur','45','Car. Autopista Panamericana Sur KM 45 - Punta Negra - Lima',0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','03','0000','LOCALSERV','Centro Huaylas-PDVF',NULL,NULL,NULL,NULL,'CAR. PANAMERICANA SUR KM. 19.8 LIMA - LIMA - VILLA EL SALVADOR',100);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','18','0000','LOCALSERV','Jockey Club-PDFV',NULL,NULL,NULL,NULL,NULL,100);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','19','0000','LOCALSERV','Centro Playa-PDVF',NULL,NULL,NULL,NULL,'CAR. PANAMERICANA SUR KM. 21.5 LIMA - LIMA - VILLA EL SALVADOR',100);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','20','0000','LOCALSERV','Boulevard Asia-PDVF',NULL,NULL,NULL,NULL,NULL,100);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','21','0000','LOCALSERV','PDVM1',NULL,NULL,NULL,NULL,NULL,0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','22','0000','LOCALSERV','PDVM2',NULL,NULL,NULL,NULL,NULL,0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','23','0000','LOCALSERV','PDVM3',NULL,NULL,NULL,NULL,NULL,0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','24','0000','LOCALSERV','PDVM4',NULL,NULL,NULL,NULL,NULL,0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','25','0000','LOCALSERV','PDVM5',NULL,NULL,NULL,NULL,NULL,0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','98','0000','LOCALSERV','PORTAL_WEB',NULL,NULL,NULL,NULL,NULL,0);
            INSERT INTO aplaza (TOLLCOMPANY,PLAZA,PLAZANODE,LANENODE,NAME,TIMEREVOK,DAYCLOSED,ROAD,KM,ADDRESS,MINSTOCK) VALUES (
            '99','99','9999','LOCALSERV','MATRIZ','20160226003007',NULL,NULL,NULL,NULL,500);
        ");
    }

    public function down(MetadataInterface $schema)
    {
        //throw new \RuntimeException('No way to go down!');
        //$this->addSql(/*Sql instruction*/);
    }
}
