<?php   $this->headLink()
    ->prependStylesheet($this->linkCdn('/css/empresa/empresa.css'));
?>
<?php  $this->inlineScript()
    ->prependFile($this->linkCdn('/js/empresa/empresa.js'));
?>
<div class=" contenedor-gotas-personas">
    <div class="col-xs-12 col-sm-1 col-md-1">
    </div>
    <div class="col-xs-12 col-sm-5 col-md-5">
        <!--************** gota ePass **************//-->
            <div class="gota-epas gota-epas-empresa-prepago" href="#href_planes_prepago">
              <div class="gota-epas-titulo"><span>Pre-Pago</span></div>
              <div class="gota-epas-img ">
                <div class="gota-epas-btn"><a id="href_planes_prepago" ><span>Ver Paquetes</span><i class="fa fa-angle-right"></i></a></div>
              </div>
            </div>
        <!--************** gota ePass **************//-->
        
    </div>
    <div class="col-xs-12 col-sm-5 col-md-5 ">
        <!--************** gota ePass **************//-->
            <div class="gota-epas bg-green gota-epas-empresa-postpago" href="#id_planes_postpago">
              <div class="gota-epas-titulo"><span>Post-Pago</span></div>
              <div class="gota-epas-img gota-epas-img-transarent-green">
                <div class="gota-epas-btn"><a id="href_planes_postpago" ><span>Ver Paquetes</span><i class="fa fa-angle-right"></i></a></div>
              </div>
            </div>
        <!--************** gota ePass **************//-->
    </div>
    <div class="col-xs-12 col-sm-1 col-md-1">
    </div>
</div>
<!--**************Conoce Nuestro Plan Individual **************-->
<div class="titleEnPersona" id="href_planes_prepago">
    Conoce nuestros Paquetes Pre-Pago
</div>
<div class="col-md-12 ">


<div class="hidden-xs col-sm-1 col-md-1 margencito txtalgnright_flecha_prev">
        <a class="btn prev">
            <i class="fa fa-angle-left flechaSlider flechaSlider-left span-color-orange"></i>
        </a>
</div>

<div class="col-xs-12 col-sm-10 col-md-10">
    <div id="demo">
        <div class="">
            <div class="row">
                <div class="span12">
                    <div id="plan-pre-pago" class="owl-carousel">
                        <?php foreach($pqt1 as $k => $v){?>
                            <div class="item">  
                               
                                <!--************** paquete ePass **************//-->
                                <div class="paqueteEpass">
                                    <div class="paqueteEpass-Titulo"><span>Paquete <?php echo $k+1 ?></span></div>
                                    <div class="contenedorContenido">
                                        <div class="paqueteEpass-Contenido">
                                            <div class="paqueteEpass-Contenido-Precio new-tag"><span class="soles">S/.</span>
                                                <div class="precio"><span><?php echo number_format($v['costoTotalConTag'], 2) ?> </span><span> *</span>
                                                <div class="recarga-1tag">Recarga + 1 TAG</div>
                                                </div>
                                            </div>
                                            <!--<div class="paqueteEpass-Contenido-Recarga"><span class="texto-descriptivo-tag-new">Permite comprar máximo <?php echo $v['maxVehiculos'] ?> TAGS</span></div>-->
                                            <div class="paqueteEpass-Contenido-bloque1 "><span>Saldo para Uso</span><span class="saldo-monto">S/. <?= number_format($v['saldoUso'], 2) ?></span></div>
                                            <div class="paqueteEpass-Contenido-bloque2 ">
                                                <?php if($v['costoPromocionalTag'] > 0) { ?>
                                                    <div class="relative">
                                                        <div>Costo TAG</div>
                                                        <div class="saldo-monto tachado">
                                                            <strike>(S/.<?php echo number_format($v['costoFijoTag'], 2) ?>) </strike>
                                                        </div>
                                                    </div>
                                                    <div class="relative">
                                                        <div class="pad">Promo Verano</div>
                                                        <div class="saldo-monto top0 specialPrice">S/.<?php echo number_format($v['costoPromocionalTag'], 2) ?>             </div>
                                                    </div>
                                                <?php } else{ ?>
                                                    <div class="relative">
                                                        <div>Costo TAG</div>
                                                        <div class="saldo-monto top0 ">
                                                            S/.<?php echo number_format($v['costoFijoTag'], 2) ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                            <div class="paqueteEpass-Contenido-bloque3 sinDashed"><span>Tasa Recarga</span><span class="saldo-monto"> S/.<?= number_format($v['tasaRecarga'], 2) ?></span></div>
                                            <div class="paqueteEpass-Contenido-VerMas">
                                                <form id="afiliacion<?php echo $k+1?>" method="POST" action="/paquete-empresas">
                                                    <input type="hidden" name="idPlan" value="<?php echo $v['planId']?>"/>
                                                    <input type="hidden" name="nombrePlan" value="<?php echo $v['namePlan']?>"/>
                                                    <input type="hidden" name="monto" value="<?php echo $v['costoTotalConTag']?>"/>
                                                    <input type="hidden" name="max_vehiculos" value="<?php echo $v['maxVehiculos']?>"/>
                                                </form>
                                                <span class="" onclick="enviar(<?php echo $k+1?>)">Afíliate</span></div>
                                        </div>
                                    </div>
                                    <div class="contenedor-msj" data-toggle="modal" data-target="#modal_pasos_recarga_automatica">

                                </div>

                                </div>
                                <!--************** paquete ePass **************//-->

                                
                            </div>
                            <?php }?>
                    </div>
                </div>
            </div>
        </div>

    </div>
<div class="contenedor-msj" data-toggle="modal" data-target="#modal_pasos_recarga_automatica">
    <div class="msj-paquete bg-orange-epass whitePointer">
        <span>Recuerda: Puedes solicitar la Recarga Automática al momento de afiliarte, sólo deberás seguir los pasos que te indicamos </span>
        <a href="">aquí</a>
    </div>
</div>
</div>
<div class="hidden-xs col-sm-1 col-md-1 margencito">
        <a class="btn next">
            <i class="fa fa-angle-right flechaSlider flechaSlider-right span-color-orange"></i>
        </a> 
</div>

    
</div>

<div class="dashedLine"></div>

<div class="titleEnPersona" id="id_planes_postpago">
    Conoce nuestros Paquetes Post-Pago
</div>
<div class="hidden-xs col-sm-1 col-md-1 margencito txtalgnright_flecha_prev">
        <a class="btn prev-post">
            <i class="rigth-arrow fa fa-angle-left flechaSlider flechaSlider-left span-color-green"></i>
        </a>
</div>
<div class="col-xs-12 col-sm-10 col-md-10">

    <div id="demo">
        <div class="">
            <div class="row">
                <div class="span12">
                    <div id="plan-post-pago" class="owl-carousel">
                        <div class="item">
                        <!--************** paquete ePass **************//-->
                            <div class="paqueteEpass">
                                <div class="paqueteEpass-Titulo pack-epass-bggreen"><span>Paquete 1</span></div>
                                <div class="contenedorContenido pack-epass-bordergreen">
                                    <div class="paqueteEpass-Contenido">
                                        <div class="paqueteEpass-Contenido-Precio pack-epass-bggreen">
                                            <div class="precio sinPorcentaje"><span>Cliente A </span></div>
                                        </div>

                                        <div class="paqueteEpass-Contenido-Recarga padding0"><span></span></div>
                                        <div class="paqueteEpass-Contenido-bloque1 dashed-green"><span>Tasa</span><span class="saldo-monto">5.50%</span></div>
                                        <div class="paqueteEpass-Contenido-bloque2 dashed-green">
                                            <div class="relative">
                                                <div>Consumo</div>
                                                <div class="saldo-monto tachado">

                                                </div>
                                            </div>
                                            <div class="relative">
                                                <div class="pad">Mínimo</div>
                                                <div class="saldo-monto top0 specialPrice">----------       </div>
                                            </div>
                                        </div>
                                        <div class="paqueteEpass-Contenido-bloque2 sinDashed">
                                            <div class="relative">
                                                <div>Quincenal</div>
                                                <div class="saldo-monto tachado">

                                                </div>
                                            </div>
                                            <div class="relative">
                                                <div class="pad">máximo</div>
                                                <div class="saldo-monto top0 specialPrice">S/.3,000.00       </div>
                                            </div>
                                        </div>
                                        <div class="paqueteEpass-Contenido-VerMas border-green-rgba bg-green-rgba"><span class="pack-epass-bggreen" data-toggle="modal" data-target="#modal_post_pago_recarga_consulta">Consultar</span></div>
                                    </div>
                                </div>
                            </div>
                        <!--************** paquete ePass **************//-->
                    </div>
                    <div class="item">
                        <!--************** paquete ePass **************//-->
                        <div class="paqueteEpass">
                            <div class="paqueteEpass-Titulo pack-epass-bggreen"><span>Paquete 2</span></div>
                            <div class="contenedorContenido pack-epass-bordergreen">
                                <div class="paqueteEpass-Contenido">
                                    <div class="paqueteEpass-Contenido-Precio pack-epass-bggreen">
                                        <div class="precio sinPorcentaje"><span>Cliente B </span></div>
                                    </div>

                                    <div class="paqueteEpass-Contenido-Recarga padding0"><span></span></div>
                                    <div class="paqueteEpass-Contenido-bloque1 dashed-green"><span>Tasa</span><span class="saldo-monto">4.50%</span></div>
                                    <div class="paqueteEpass-Contenido-bloque2 dashed-green">
                                        <div class="relative">
                                            <div>Consumo</div>
                                            <div class="saldo-monto tachado">

                                            </div>
                                        </div>
                                        <div class="relative">
                                            <div class="pad">Mínimo</div>
                                            <div class="saldo-monto top0 specialPrice">S/. 3,001.00       </div>
                                        </div>
                                    </div>
                                    <div class="paqueteEpass-Contenido-bloque2 sinDashed">
                                        <div class="relative">
                                            <div>Quincenal</div>
                                            <div class="saldo-monto tachado">

                                            </div>
                                        </div>
                                        <div class="relative">
                                            <div class="pad">máximo</div>
                                            <div class="saldo-monto top0 specialPrice">S/.10,000.00       </div>
                                        </div>
                                    </div>
                                    <div class="paqueteEpass-Contenido-VerMas border-green-rgba bg-green-rgba"><span class="pack-epass-bggreen" data-toggle="modal" data-target="#modal_post_pago_recarga_consulta">Consultar</span></div>
                                </div>
                            </div>
                        </div>
                        <!--************** paquete ePass **************//-->
                    </div>
                    <div class="item">
                        <!--************** paquete ePass **************//-->
                        <div class="paqueteEpass">
                            <div class="paqueteEpass-Titulo pack-epass-bggreen"><span>Paquete 3</span></div>
                            <div class="contenedorContenido pack-epass-bordergreen">
                                <div class="paqueteEpass-Contenido">
                                    <div class="paqueteEpass-Contenido-Precio pack-epass-bggreen">
                                        <div class="precio sinPorcentaje"><span>Cliente C </span></div>
                                    </div>

                                    <div class="paqueteEpass-Contenido-Recarga padding0"><span></span></div>
                                    <div class="paqueteEpass-Contenido-bloque1 dashed-green"><span>Tasa</span><span class="saldo-monto">3.50%</span></div>
                                    <div class="paqueteEpass-Contenido-bloque2 dashed-green">
                                        <div class="relative">
                                            <div>Consumo</div>
                                            <div class="saldo-monto tachado">

                                            </div>
                                        </div>
                                        <div class="relative">
                                            <div class="pad">Mínimo</div>
                                            <div class="saldo-monto top0 specialPrice">S/.10,001.00       </div>
                                        </div>
                                    </div>
                                    <div class="paqueteEpass-Contenido-bloque2 sinDashed">
                                        <div class="relative">
                                            <div>Quincenal</div>
                                            <div class="saldo-monto tachado">

                                            </div>
                                        </div>
                                        <div class="relative">
                                            <div class="pad">máximo</div>
                                            <div class="saldo-monto top0 specialPrice">Más       </div>
                                        </div>
                                    </div>
                                    <div class="paqueteEpass-Contenido-VerMas border-green-rgba bg-green-rgba"><span class="pack-epass-bggreen" data-toggle="modal" data-target="#modal_post_pago_recarga_consulta">Consultar</span></div>
                                </div>
                            </div>
                        </div>
                        <!--************** paquete ePass **************//-->
                    </div>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
        
    
   
        
        
    
    
        

    
    <div class="contenedor-msj" data-toggle="modal" data-target="#modal_pasos_recarga_automatica">
        <div class="msj-paquete bg-green-epass">
            <span>Recuerda: Puedes solicitar la Recarga Automática al momento de afiliarte, sólo deberás seguir los pasos que te indicamos </span>
            <a href="">aquí</a>
        </div>
    </div>
</div>
<div class="hidden-xs col-sm-1 col-md-1 margencito">
        <a class="btn next-post">
            <i class="left-arrow fa fa-angle-right flechaSlider flechaSlider-right span-color-green"></i>
        </a> 
</div>
</div>
<div class="texto-asterisco">
    (*) El costo del TAG por vehículo afiliado al contrato será adicionado al monto del paquete elegido y el mismo será cobrado al concluir su afiliación
</div>
<div class="col-md-12 publicidadEpass publicidadEpass-empresa" >
    <div class="border-blanco row">
        <div class="col-xs-12 col-sm-12 col-md-3">
            <div class="requi_afiliacion">Requisitos para la Afiliación Post-Pago</div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-1 center">
            <img class="flecha-requisitos-afiliacion" src="<?php echo $this->linkCdn('/img/flecha-verde.png') ?>" >
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 center">
             <ul class="lista-afiliate-aqui">
                 <li>
                     <span>1.-</span>
                     <span> Razón Social</span>
                 </li>
                 <li>
                     <span>2.- </span>
                     <span>Ruc</span>
                 </li>
                 <li>
                     <span>3.- </span>
                     <span>Poder Responsable Legal</span>
                 </li>
             </ul>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-5 center">
            <ul class="lista-afiliate-aqui lista-afiliate-aqui_paso_4">
                 <li>
                     <span>4.-</span>
                     <span>Carta Fianza</span>
                 </li>
                 <li>
                     <span>5.- </span>
                     <span>Relación de Vehículos</span>
                 </li>
                 <li>
                     <span>6.- </span>
                     <span>Llamar a la Central de Atención al Cliente 249-7222</span>
                 </li>
             </ul>
        </div>
    </div>
    
</div>
<script type="text/javascript">
    function enviar(id){
        var form = document.getElementById("afiliacion"+id);
        form.submit();        
    }
</script>