<?php  $this->headLink()
    ->prependStylesheet($this->linkCdn('/css/administrador/micuenta.css'))
     /*->prependStylesheet($this->linkCdn('/css/administrador/reportes.css'))*/
     ->prependStylesheet($this->linkCdn('/css/afiliate/afiliate.css'))
    /* ->prependStylesheet($this->linkCdn('/css/general/general.css'))*/
     ?>
<?php  $this->headScript()                                    
    ->prependFile($this->linkCdn('/js/afiliate/afiliate.js'))
    /*->prependFile($this->linkCdn('/js/general/general.js'))*/; ?> 
<div class="row breadcrumb-epas-dashboard">
    <div class="col-xs-12  col-sm-3 col-md-2 pest-title">Proceso de Afiliación</div>
    <div class="col-xs-6  col-sm-3 col-md-2 pest-active">Paso 1</div>
    <div class="col-xs-6  col-sm-3 col-md-2 pest-desactive">Paso 2</div>
    <div class="col-xs-6  col-sm-3 col-md-2 pest-desactive">Paso 3</div>
</div>
<div class="contenidoAfiliate">
    <div class="titulo">Recuerde que</div>
    <p class="letraAfiliate">
        Para obtener nuestro servicio, sólo tiene que completar el siguiente formulario. Una vez que termine el proceso de afiliación, en un plazo no mayor de 72 horas recibirá su e-pass.
    </p>
    <div class="contenedorComponenteCuadroFlecha">
        <!--************** publicidad epassFlecha **************//-->
        <div class="ContenedorCuadroFlecha">
            <div class="titulo-epassFlecha titulo-epassFlecha-paso1">Paquete Seleccionado</div>
            <div class="contenedorPubli">
                <div class="titulo-Naranja">Plan Compartido</div>
                <div class="flechaConCss"><i class="fa fa-long-arrow-right"></i></div>
                <div class="titulo-Naranja">Paquete de  S/. 50.00</div>
            </div>
        </div>
        <!--************** publicidad epassFlecha **************//-->
    </div>
    <div class="contenedorComponenteFormularioEpass">
        <!--************** formulario ePass **************//-->
        <div class="contenedorFormularioEpass">
            <div class="subContenedorFormularioEpass">
                <span class="spanEncima">Datos Personales</span>
                <div class="contenedorInputsEpass row">
                    <div class="form-inline">
                        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                            <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-4">Nombre de Titular :</label>
                            <div class="col-xs-12 col-sm-12 col-md-8">
                                <input type="text" disabled class="disabled-style imputEpass col-xs-12 col-sm-12 col-md-12">                            
                            </div>
                        </div>
                        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                            <label for="apellidos" class="spanEpass col-xs-12 col-sm-12 col-md-4">Apellidos del Titular :</label>
                            <div class="col-xs-12 col-sm-12 col-md-8">
                                <input disabled type="text" class="disabled-style imputEpass col-xs-12 col-sm-12 col-md-12" >                            
                            </div>
                        </div>
                    </div>
                    <div class="form-inline">
                        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                            <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Tipo de Documento :</label>
                            <div class="col-xs-12 col-sm-12 col-md-8">
                                <select  class="disabled-style select_tipo_documento imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker" disabled>
                                    <option value="">Seleccionar Documento</option>
                                    <option value="0">RUC</option>
                                    <option value="1">DNI</option>
                                    <option value="2">CE</option>
                                    <option value="3">PASAPORTE</option>
                                </select>
                            </div>
                        </div>
                        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                            <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Nro Documento :</label>
                            <div class="col-xs-12 col-sm-12 col-md-8">
                                <input type="text"  class="disabled-style imputEpass col-xs-12 col-sm-12 col-md-12" disabled />                            
                            </div>
                        </div>
                    </div>
                    <div class="form-inline">
                        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
                            <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Correo :</label>
                            <div class="col-xs-12 col-sm-12 col-md-10">
                                <input type="text"  class="disabled-style slSinMarg imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker" disabled />                            
                            </div>
                        </div>
                    </div>
                    <!--
                    <div class="form-inline">
                        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                            <label for="contrasenia" class="spanEpass col-xs-12 col-sm-12 col-md-4">Contraseña :</label>
                            <div class="col-xs-12 col-sm-12 col-md-8">
                                <input type="password" name="txtContrasenia" id="txtContrasenia" placeholder="Ingrese contraseña segura" class="imputEpass col-xs-12 col-sm-12 col-md-12" required="required" value="" aria-required="true">                            
                            </div>
                        </div>
                        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                            <label for="confirmar_contrasenia" class="spanEpass col-xs-12 col-sm-12 col-md-4">Confirmar Contraseña :</label>
                            <div class="col-xs-12 col-sm-12 col-md-8">
                                <input type="password" name="txtConfirmaContrasenia" id="txtConfirmaContrasenia" placeholder="Repita contraseña" class="imputEpass col-xs-12 col-sm-12 col-md-12" required="required" value="" aria-required="true">                            
                            </div>
                        </div>
                    </div>-->
                </div>
            </div>
           
            <div class="subContenedorFormularioEpass top3em">
                <span class="spanEncima">Forma de Entrega</span>
                <div class="contenedorInputsEpass row">
                    <div class="form-inline txt-center">
                        <label class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group spanEpass"><input type="radio" name="radTipo" class="imputEpass radioEnvioRetiro" value="0">Retiro en punto de Venta</label><label class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group spanEpass"><input type="radio" name="radTipo" class="imputEpass radioEnvioRetiro" value="1">Envío a Domicilio</label>                    
                    </div>
                </div>
            </div>
            <div class="form-venta">
            </div>
            <div class="form-domicilio top3em">
                <div class="subContenedorFormularioEpass">
                    <span class="spanEncima">Dirección</span>
                    <div class="contenedorInputsEpass row">
                        <div class="form-inline">
                            <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Departamento:</label>
                                <div class="col-xs-12 col-sm-12 col-md-8">
                                    <select name="idDpto" id="idDpto" class="imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker">
                                        <option value="0">Seleccionar Departamento</option>
                                        <option value="1">AMAZONAS</option>
                                        <option value="2">ANCASH</option>
                                        <option value="3">APURIMAC</option>
                                        <option value="4">AREQUIPA</option>
                                        <option value="5">AYACUCHO</option>
                                        <option value="6">CAJAMARCA</option>
                                        <option value="7">CALLAO</option>
                                        <option value="8">CUSCO</option>
                                        <option value="9">HUANCAVELICA</option>
                                        <option value="10">HUANUCO</option>
                                        <option value="11">ICA</option>
                                        <option value="12">JUNIN</option>
                                        <option value="13">LA LIBERTAD</option>
                                        <option value="14">LAMBAYEQUE</option>
                                        <option value="15">LIMA</option>
                                        <option value="16">LORETO</option>
                                        <option value="17">MADRE DE DIOS</option>
                                        <option value="18">MOQUEGUA</option>
                                        <option value="19">PASCO</option>
                                        <option value="20">PIURA</option>
                                        <option value="21">PUNO</option>
                                        <option value="22">SAN MARTIN</option>
                                        <option value="23">TACNA</option>
                                        <option value="24">TUMBES</option>
                                        <option value="25">UCAYALI</option>
                                    </select>
                                </div>
                            </div>
                            <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Provincia :</label>
                                <div class="col-xs-12 col-sm-12 col-md-8">
                                    <select name="idProvin" id="idProvin" class="imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker">
                                        <option value="0">Elija Departamento</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-inline">
                            <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Distrito :</label>
                                <div class="col-xs-12 col-sm-12 col-md-8">
                                    <select name="idDistrito" id="idDistrito" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
                                        <option value="0">Elija Provincia</option>
                                    </select>
                                </div>
                            </div>
                            <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Calle/ Av/ Jr :</label>
                                <div class="col-xs-12 col-sm-12 col-md-8">
                                    <input type="text" name="txtNombVia" id="txtNombVia" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚäëïöü' ]+$/gi" placeholder="Ingrese Calle/ Av/ Jr:" class="imputEpass col-xs-12 col-sm-12 col-md-12" value="">                                
                                </div>
                            </div>
                        </div>
                        <div class="form-inline">
                            <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Número :</label>
                                <div class="col-xs-12 col-sm-12 col-md-8">
                                    <input type="text" name="txtNumVia" id="txtNumVia" maxlength="6" placeholder="Ingrese número:" class="imputEpass col-xs-12 col-sm-12 col-md-12" value="">                                
                                </div>
                            </div>
                            <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Dpto/ Int :</label>
                                <div class="col-xs-12 col-sm-12 col-md-8">
                                    <input type="text" name="txtDptoVia" id="txtDptoVia" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚäëïöü' ]+$/gi" placeholder="Ingrese Dpto. Int:" class="imputEpass col-xs-12 col-sm-12 col-md-12" value="">                                
                                </div>
                            </div>
                        </div>
                        <div class="form-inline">
                            <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
                                <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Urbanización :</label>
                                <div class="col-xs-12 col-sm-12 col-md-10">
                                    <input type="text" name="txtUrbanizacion" id="txtUrbanizacion" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚäëïöü' ]+$/gi" placeholder="Ingrese Urbanización" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker" value="">                                
                                </div>
                            </div>
                        </div>
                        <div class="form-inline">
                            <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
                                <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Referencia :</label>
                                <div class="col-xs-12 col-sm-12 col-md-10">
                                    <input type="text" name="txtReferencia" id="txtReferencia" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚäëïöü' ]+$/gi" placeholder="referencia" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker" value="">                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="subContenedorFormularioEpass cont_check">
            <div class="contenedorInputsEpass row">
                <div class="form-inline">
                    <div class="camp_checkbox col-xs-12 col-sm-6 col-md-6">
                        <div>
                            <input type="hidden" name="CkTerminos" value="0"><input type="checkbox" name="CkTerminos" id="CkTerminos" required="required" value="1" aria-required="true">                                    <span class="inline-block span_check">
                            <span class="inline-block marg">Acepto los &nbsp;</span>
                            <a href="#">términos y condiciones</a>
                            <span>&nbsp; del servicio</span>
                            </span>
                        </div>
                        <div>
                            <input type="hidden" name="CkNovedades" value="0"><input type="checkbox" name="CkNovedades" id="CkNovedades" value="1"><span class="inline-block marg span_check">Quiero recibir novedades de e-pass</span>
                        </div>
                    </div>
                    <div class="btn_siguientePaso col-xs-12 col-sm-6 col-md-6">
                        <button type="submit" name="btnSgtPaso" class="submit_sgtpaso" value="">Siguiente Paso</button>                        
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" name="idPlan" id="idPlan" value="39">        <input type="hidden" name="txtMonto" id="txtMonto" value="50.00">
        <!--************** formulario ePass **************//-->
    </div>
</div>
