<?php
// Generated by Zend Framework 2
return array(
    'ModPruebas\Model\Collection\UsuariosCollection' => __DIR__ . '/src/ModPruebas/Model/Collection/UsuariosCollection.php',
    'ModPruebas\Model\Table\UsersTable'              => __DIR__ . '/src/ModPruebas/Model/Table/UsersTable.php',
    'ModPruebas\Controller\IndexController'          => __DIR__ . '/src/ModPruebas/Controller/IndexController.php',
    'ModPruebas\Module'                              => __DIR__ . '/Module.php',
);