<footer>
    <div class="footer_barra"></div>
    <div id="atencion_cliente">
        Central de Atención al Cliente<br>
        <span class="icon icon_phone"></span>0800-45045 o 249-7222 <br>
        <span class="icon icon_email"></span></i> atencionalcliente@epass.pe
    </div>
    <div  class="content row v-center-lg v-center-md text-xs-center ">
        <div class="footer_item col-md-3 col-sm-6">
           <img class="img_logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass"> 
           <br>
           <br>
           © Todos los derechos reservados, 2016.
        </div>
        <div class="footer_item col-md-3 col-sm-6">
            <i class="fa fa-building fa-lg"></i> 
            Panamericana Sur km 19,5 <br>(sentido sur)
            Villa El Salvador - Perú <br>
            <i class="fa fa-envelope-o fa-lg"></i> atencionalcliente@epass.pe <br>
        </div>
        <div class="footer_item col-md-3 col-sm-6">
            <a href="<?php echo $this->basePath() ?>/front/index/contactanos"><i class="fa fa-headphones fa-lg"></i> Contáctanos</a>
            <br>
            <br>
            
            <i class="fa fa-phone fa-lg"></i> 0800-45045 o 249-7222
        </div>
        <div class="footer_item col-md-3 col-sm-6">
            <a id="libro_reclamacion" target="_blank"  href="<?php echo $this->basePath() ?>/front/reclamaciones/index">
                <img src="<?php echo $this->linkCdn('/img/libro_reclamacion.svg') ?>" >
                <div class="libro_reclamacion_text" >
                    Libro de <br>
                    Reclamaciones
                </div>
            </a>            
        </div>
    </div>

</footer>
