<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/img/ico.png')))

                        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->linkCdn('/css/main.css'))
                        ->prependStylesheet($this->linkCdn('/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->linkCdn('/js/bootstrap.min.js'))
            ->prependFile('http://jqueryvalidation.org/files/dist/jquery.validate.min.js')
            ->prependFile($this->linkCdn('/js/jquery.min.js'))
            ->prependFile($this->linkCdn('/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->linkCdn('/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>

    </head>
    <body>
        <?php 
            if($this->cuenta)
            {
                echo $this->partial('layout/header_cuenta');
            }
            else if($this->reclamaciones)
            {
                echo $this->partial('layout/header_reclamaciones');
            }
            else
            {
                echo $this->partial('layout/header');
            }
        ?>                
         <?php echo $this->content; ?>

        <?php 
            if($this->reclamaciones)
            {
                
            }
            else
            {
                echo $this->partial('layout/footer');
            }
        ?>
        
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript" src="<?php echo $this->linkCdn('/js/main.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->linkCdn('/js/jquery.message_es.js') ?>"></script>  
    </body>
</html>
