<?php  $this->headLink()    
    ->prependStylesheet($this->linkCdn('/css/afiliate/afiliate.css'));
?>
<?php  $this->inlineScript()
    ->prependFile($this->linkCdn('/js/afiliate/afiliate.js')); ?>
<?php
$session = $this->session;
//Cargar de formulario
$form = $this->formRegistroAvanzado;
$form->prepare();
$form->setAttribute('method', 'post')
    ->setAttribute('action', '')
    ->setAttribute('class', 'formulario-afiliate')
;
echo $this->form()->openTag($form);

$cant = 1;
if ($session->offsetExists('numVehicle')) {
    $cant = $session->offsetGet('numVehicle');
}
?>
<script type="text/javascript">
    var maxCarros = "<?php echo $session->maxVehiculos; ?>" ;
    var cantCarros = "<?php echo $cant; ?>" ;
</script>
<div class="contenidoAfiliate">
    <div class="titulo">Recuerde que</div>
    <p class="letraAfiliate">
        Para obtener nuestro servicio, sólo tiene que completar el siguiente formulario. Una vez que termine el proceso de afiliación, en un plazo no mayor de 72 horas recibirá su <i class=italic>e-pass</i>.
    </p>
    <div class="contenedorComponenteCuadroFlecha">
        <!--************** publicidad epassFlecha **************//-->
        <div class="ContenedorCuadroFlecha">
            <div class="titulo-epassFlecha titulo-epassFlecha-paso1">Paquete Seleccionado</div>
            <div class="contenedorPubli">
                <div class="titulo-Naranja">Plan <?php echo $session->title; ?></div>
                <div class="flechaConCss"><i class="fa fa-long-arrow-right"></i></div>
                <div class="titulo-Naranja">Paquete de  S/. <?php echo $session->costoSinTag; ?></div>
            </div>
        </div>
        <!--************** publicidad epassFlecha **************//-->
    </div>
    <div class="contenedorComponenteFormularioEpass">
        <!--************** formulario ePass **************//-->

        <div id="contenedorVehiculosAgregar" class="subContenedorFormularioEpass top2">
            <span class="spanEncima titulo-vehiculos">Información de los Vehículos afiliados</span>
            <div class="btn-aumentarVehiculo">
                <div  id="contadorVehiculos">1</div>
                <button id="agregarOtroVehiculo" type="button" class="btn_siguientePaso btn btn-info btn-add-car">Agregar otro vehículo</button>
            </div>
            <div id="contenedorVehiculosAgregados">
                <!--
                <?php if($cant > 1){ ?>
                    <?php for($i=2;$i<=$cant;$i++){ ?>
                        <?php $k = $i -1; ?>

                        <div class="subContenedorFormularioEpass top2em">
                            <span id="vehiculo-nr<?php echo $k; ?>-close" class="cerrarVehiculo" onclick="cerrarVehiculo(this,<?php echo $i; ?>);" data-position="<?php echo $i; ?>"><i class="fa fa-times"></i></span>

                            <span class="spanEncima">Vehículo</span>
                            <div class="contenedorInputsEpass row">
                                <div class="form-inline">
                                    <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                        <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Tipo de Vehículo :</label>
                                        <div class="col-xs-12 col-sm-12 col-md-8">
                                            <?php echo $this->formElement($form->get("idTipoVehiculo".$i)->setAttribute('class', 'imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker')->setValue($session->{"idTipoVehiculo".$i})); ?>
                                        </div>
                                    </div>
                                    <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                        <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Marca :</label>
                                        <div class="col-xs-12 col-sm-12 col-md-8">
                                            <?php echo $this->formElement($form->get("idMarca".$i)->setAttribute('class', 'imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker')->setValue($session->{"idMarca".$i})); ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-inline">
                                    <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                        <label for="contrasenia" class="spanEpass col-xs-12 col-sm-12 col-md-4">Placa :</label>
                                        <div class="col-xs-12 col-sm-12 col-md-8">
                                            <?php echo $this->formElement($form->get("txtPlaca".$i)->setAttribute('placeholder', 'Ejem: A8D038')->setAttribute('class', 'ajax-paca imputEpass col-xs-12 col-sm-12 col-md-12')->setAttribute('value',$session->{"txtPlaca".$i})); ?>
                                            <div id="txtPlacamensaje" class="error txtPlacamensaje-class"></div>
                                            <input type="hidden" id="hidden-vehiculo" class="hidden-vehiculo" value="1"></input>
                                        </div>

                                    </div>
                                    <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                        <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Modelo :</label>
                                        <div class="col-xs-12 col-sm-12 col-md-8">
                                            <?php echo $this->formElement($form->get("idModelo".$i)->setAttribute('class', 'imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker')->setValue($session->{"idModelo".$i})); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                <?php }  ?>-->
                <div id="vehiculo1" >
                    <div class="subContenedorFormularioEpass top2em">
                        <span class="spanEncima">Vehículo</span>
                        <div class="contenedorInputsEpass row">
                            <div class="form-inline">
                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                    <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Tipo de Vehículo :</label>
                                    <div class="col-xs-12 col-sm-12 col-md-8">
                                        <?php echo $this->formElement($form->get("idTipoVehiculo")->setAttribute('class', 'imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker')->setValue($session->idTipoVehiculo)); ?>
                                    </div>
                                </div>
                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                    <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Marca :</label>
                                    <div class="col-xs-12 col-sm-12 col-md-8">
                                        <?php echo $this->formElement($form->get("idMarca")->setAttribute('class', 'imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker')->setValue($session->idMarca)); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-inline">
                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                    <label for="contrasenia" class="spanEpass col-xs-12 col-sm-12 col-md-4">Placa :</label>
                                    <div class="col-xs-12 col-sm-12 col-md-8">
                                        <?php echo $this->formElement($form->get("txtPlaca")->setAttribute('placeholder', 'Ejem: A8D038')->setAttribute('class', 'ajax-paca imputEpass col-xs-12 col-sm-12 col-md-12')->setAttribute('value',$session->txtPlaca)); ?>
                                        <div id="txtPlacamensaje" class="txtPlacamensaje-class error"></div>
                                        <input type="hidden" id="hidden-vehiculo" class="hidden-vehiculo" value="1"></input>
                                    </div>
                                </div>
                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
                                    <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Modelo :</label>
                                    <div class="col-xs-12 col-sm-12 col-md-8">
                                        <?php echo $this->formElement($form->get("idModelo")->setAttribute('class', 'imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker')->setValue($session->idModelo)); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-inline">
                            <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
                                    <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Color :</label>
                                    <div class="col-xs-12 col-sm-12 col-md-10 tick-316">
                                        <!--input id="txtColor" type="text" name="txtColor" id="" data- maxlength="16" placeholder="Ingrese Color" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker" value=""-->
                                        <?php echo $this->formElement($form->get("txtColor")->setAttribute('maxlength', 14)->setAttribute('placeholder', 'Ingrese el color de Vehículo')->setAttribute('class', 'slSinMarg imputEpass col-xs-12 col-sm-12 col-md-12 selectpicker')->setValue($session->txtColor)); ?>
                                    </div>
                                    
                                </div>                        
                        </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row botoneras">
            
            <div class="col-xs-12 col-sm-6 col-md-3 ">
            </div>
            <div class="btn_siguientePaso col-xs-12 col-sm-6 col-md-3 ">
                <a onclick="history.back(-1)">
                    <i class="fa fa-angle-left"></i>
                    <span>Paso Anterior</span>
                </a>
            </div>
            <div class="btn_siguientePaso col-xs-12 col-sm-6 col-md-3 ">
                <?php echo $this->formElement($form->get("btnSgtPaso")
                        ->setAttribute('id', 'submit_sgtpaso_afi_emp_vehi')
                        ->setAttribute('class', 'submit_sgtpaso')->setAttribute('id', 'id_form_placas_iguales')->setOptions(array('label' => 'Pagar'))); ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        <!--************** formulario ePass **************//-->
    </div>
</div>