<div id="banner" class="banner-beneficios">
    <img class="img-lazy" data-original="<?php echo $this->linkCdn('/img/beneficios_origin.jpg') ?>" 
    src="<?php echo $this->linkCdn('/img/beneficiosx30.jpg') ?>" >
    <div id="box">            
            Permite realizar el pago <br>
            de sus peajes y otros <br>
            servicios autorizados <br>
             de manera más cómoda.
    </div>
   
</div> 
<div class="container">
    <div id="adquirir_beneficios" class="info" >
        <h2>¿Cuáles son los Beneficios al adquirir el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
        <div class="info_content inline-block-middle">
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Los clientes ya no necesitarán de efectivo para el pago del peaje y otros servicios autorizados.</div>
            </div>
            <div class="item"><div class="icon item_icon"></div>
                <div class="item_text">Paso por una vía exclusiva sin detenerse para hacer el  pago.</div>
            </div>
            <div class="item"><div class="icon item_icon"></div>
                <div class="item_text">Las recargas se podrán realizar por cargo automático.</div>
            </div>
        </div>
        <div class="inline-block-middle">
            <img class="info_img icon_peaje1-top"  src="<?php echo $this->linkCdn('/img/peaje.png') ?>" >
            <span class="icon icon_car"></span>
        </div>
        
    </div>

    <div class="line"></div>

    <div class="info" >
        <div class="inline-block-middle">
            <h2>¿Dónde puedes usar  el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
            <div class="info_content">
    Brinda al cliente el paso fácil, cómodo y simple por los peajes de Rutas de Lima, concesión que tiene a su cargo la operación y mantenimiento de la carretera Panamericana Norte, desde el Óvalo Habich hasta el Intercambio de Ancón, y de la carretera Panamericana Sur, desde el Trébol de Javier Prado hasta el Puente Pucusana.
            </div>
        </div>
        <div class="inline-block-middle">            
            <span class="icon icon_foco info_img icon_foco-top"></span>
        </div>                
    </div>

    <div class="line"></div>

    <div class="info" >
        <h2>¿Qué peajes administra Rutas de Lima?</h2>
        <div class="info_content inline-block-middle">
            El cliente podrá hacer uso de los Beneficios de <spam class="epas-line"><i class=italic>e-pass</i></spam> en los siguientes peajes:
            <div class="row">
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Arica<br>
                        (Panamericana Sur Km. 35)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Huaylas<br>
                        (Panamericana Sur Km. 18.5)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Chillón<br>
                        (Panamericana Norte Km. 25)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Punta Negra<br>
                        (Panamericana Sur Km. 45.1) </div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Conchán<br>
                        (Panamericana Sur Km. 25.5)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Villa<br>
                        (Panamericana Sur Km. 19.5)</div>
                </div>
            </div>
        </div>
        <div class="info_content inline-block-middle">
            <img class="info_img icon_peaje-top"  src="<?php echo $this->linkCdn('/img/peaje.png') ?>" >    
        </div>        
    </div>

</div> <!-- /container -->