<div id="banner" class="banner-como">
    <img class="img-lazy" data-original="<?php echo $this->linkCdn('/img/como_colocar_tu_epass_origin.jpg') ?>" 
    src="<?php echo $this->linkCdn('/img/como_colocar_tu_epassx30.jpg') ?>" >

  <div id="box">
      El TAG (dispositivo electrónico) <br>
      está diseñado para que pueda <br>
      ser utilizado en vehículos <br>
      livianos, pesados y públicos.
  </div>

</div>

<div class="container">

  <div class="info" >
    <h2>¿Cuáles son los pasos para poner el TAG en su vehículo?</h2>
    <div class="info_content">
      <div class="item"><span class="icon item_icon"></span>
        <div class="item_text">Es muy sencillo. El TAG se coloca debajo del espejo retrovisor.</div>
      </div>
      <div class="item"><span class="icon item_icon"></span>
        <div class="item_text">Siga sólo estos tres pasos para poner el TAG en su vehículo:</div>
      </div>
      <img  src="<?php echo $this->linkCdn('/img/como_1.png') ?>" >
    </div>
  </div>

  <div class="line"></div>

  <div class="info" >
    <h2>Recuerde que ...</h2>
    <div class="info_content">
      <img  src="<?php echo $this->linkCdn('/img/como_2.png') ?>" >
    </div>
  </div>


</div> <!-- /container -->