<div id="banner" class="banner-donde">
    <img class="img-lazy" data-original="<?php echo $this->linkCdn('/img/donde_adquirir_origin.jpg') ?>" 
    src="<?php echo $this->linkCdn('/img/donde_adquirirx30.jpg') ?>" >
  <div id="box">
      Si Usted está interesado <br>
      en adquirir su <i class=italic>e-pass</i> lo <br>
      puede hacer <a href="#" data-target="#modal_afiliate" data-toggle="modal">aquí</a>.
  </div>
  
</div>

<div class="container">
  <div class="info" >
    <h2>¿Dónde puedo adquirir el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
    <div class="info_content">
      El usuario podrá adquirir el <i class=italic>e-pass</i> en los siguientes canales de atención:
      <div class="row">
        <div class="item col-md-4"><span class="icon item_icon"></span>
          <div class="item_text">Vía Web</div>
        </div>
        <div class="item col-md-4"><span class="icon item_icon"></span>
          <div class="item_text">Vía Telefónica</div>
        </div>
        <div class="item col-md-4"><span class="icon item_icon"></span>
          <div class="item_text">Centros de Ventas</div>
        </div>
      </div>
    </div>
    <span class="icon icon_row info_img"></span>
  </div>

  <div class="line"></div>

  <div class="info" >
    <h2>¿Cuáles son los Centros de Ventas Autorizados del <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
    <div class="info_content">
      Los centros de ventas autorizados de <spam class="epas-line"><i class=italic>e-pass</i></spam> están ubicados en:
      
      <div class="item"><span class="icon item_icon"></span>
        <div class="item_text">Km 21,5 de la Carretera Panamericana Sur, sentido sur (al costado del Touring y Automóvil Club del Perú)</div>
      </div>
    </div>
  </div>

  <div class="line"></div>

  <div class="info" >
    <h2>¿Cuáles son los Horarios de Atención en los Centros de Venta Autorizados del <spam class="epas-line"><i class=italic>e-pass</i>?</spam></h2>
    <div class="info_content">
      Los horarios de atención de los centros de ventas autorizados de <i class=italic>e-pass</i> son:
      <div class="item"><span class="icon item_icon"></span>
        <div class="item_text">Lunes a Sábado, 8:30 a.m. a 5:00 p.m.</div>
      </div>
      <div class="item"><span class="icon item_icon"></span>
        <div class="item_text">Domingo, 8:30 a.m. a 3:00 p.m</div>
      </div>      
      <div class="item"><span class="icon item_icon"></span>
        <div class="item_text">Cualquier información adicional no dude en comunicarse a la Central de Atención al Cliente: <br>
          0800-45045 o 2497222</div>
      </div>
    </div>
    <img class="info_img people_group" src="<?php echo $this->linkCdn('/img/group.png') ?>" >
  </div>

  <div class="line"></div>

  <div class="info" >
    <h2>¿Cuáles son los Medios de Pago viables para la adquisión del <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
    <div class="info_content">
      El <spam class="epas-line"><i class=italic>e-pass</i></spam> trabaja con los siguientes Medios de Pago:
      <div class="medios_pago">
        <img src="<?php echo $this->linkCdn('/img/visa2.png') ?>" >
        <img src="<?php echo $this->linkCdn('/img/master_card.png') ?>" >
        <img src="<?php echo $this->linkCdn('/img/american_express.jpg') ?>" >
        <img src="<?php echo $this->linkCdn('/img/diners_club.png') ?>" >
      </div>
      <p>Para Recargas: Web, Puntos de Venta, Vía BCP y Agentes BCP</p>
      <p>Recarga Automática: Tarjetas de Crédito y Cuenta BCP (*)</p>
      <p class="info_adicional">(*) El servicio de Recarga Automática estará habilitado próximamente. Consulte en nuestros canales de atención. </p>

    </div>
    <img class="info_img card_send" src="<?php echo $this->linkCdn('/img/card_send.png') ?>" >
  </div>

</div> <!-- /container -->