<div id="banner" class="banner-preguntas">
     <img class="img-lazy" data-original="<?php echo $this->linkCdn('/img/preguntas_frecuentes_origin.jpg') ?>" 
    src="<?php echo $this->linkCdn('/img/preguntas_frecuentesx30.jpg') ?>" >
    <div id="box">
            Aquí podrás encontrar las<br>
            respuestas a las preguntas<br>
            más frecuentes.
    </div>
    
</div>

<div class="container preguntas_frecuentes">
    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Características  y Beneficios<br>
                del <span><i class=italic>e-pass</i></span>
            </h2>
        </div>
        <div class="col-md-7">

            <h3>¿Qué es el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            Es un medio de pago electrónico que permite el paso por los peajes y otros servicios autorizados de manera más ágil y sin tener efectivo.
            <h3>¿Dónde puedo hacer uso de los Beneficios del <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            En el caso del uso dentro de la Concesionaria Rutas de Lima, el cliente puede pasar por los siguientes peajes:
            <div class="row">
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Arica<br>
                        (Panamericana Sur Km. 35)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Huaylas<br>
                        (Panamericana Sur Km. 18.5)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Chillón<br>
                        (Panamericana Norte Km. 25)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Punta Negra<br>
                        (Panamericana Sur Km. 45.1) </div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Conchán<br>
                        (Panamericana Sur Km. 25.5)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Villa<br>
                        (Panamericana Sur Km. 19.5)</div>
                </div>
            </div>
        </div>
    </div>
    <div class="line"></div>

    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Colocación y Funcionamiento de <br>
                mi <spam class="epas-line"><span><i class=italic>e-pass</i></span></spam>
            </h2>
        </div>
        <div class="col-md-7">

            <h3>¿Cómo coloco el TAG de <spam class="epas-line"><i class=italic>e-pass</i></spam> en mi vehículo?</h3>
                En el folleto informativo que recibió cuando adquirió el TAG están 
                las instrucciones para colocarlo. 
                Asimismo, puede encontrar el paso a paso en 
                www.e-pass.com <a href="<?php echo $this->url('como') ?>">(HAGA CLICK AQUÍ)</a>
            <h3>¿Cómo funciona mi <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            Si Usted ya cuenta con su TAG (dispositivo electrónico) tiene que seguir el siguiente procedimiento:
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    El vehículo se aproxima a la barrera de ingreso al peaje, estacionamiento u otro servicio autorizado.
                </div>
            </div>
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    Nuestro sistema detecta el TAG instalado en el parabrisas.
                </div>
            </div>
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    Se enciende la luz verde del semáforo y la barrera se levanta.
                </div>
            </div>
            
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    El vehículo continúa con su recorrido.
                </div>
            </div>

        </div>
    </div>
    <div class="line"></div>

    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Costos y  Vigencia <br>
                del <spam class="epas-line"><span><i class=italic>e-pass</i></span></spam>
            </h2>
        </div>
        <div class="col-md-7">

            <h3>¿Cuál es el precio del TAG <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            El precio es de S/.20. En caso sufra un daño por la manipulación del cliente, la reposición tiene un valor de S/.20.
            <h3>¿El monto recargado tiene fecha de vencimiento?</h3>
            No tiene fecha de vencimiento. Sin embargo, a partir del año de realizada la recarga se cobrará una tasa de mantenimiento.
            <h3>¿Qué es la tasa de mantenimiento?</h3>
            La tasa de mantenimiento se activará en caso el Cliente <span><spam class="epas-line"><i class=italic>e-pass</i></spam> no registre transacciones o recargas al finalizar 12 meses completos. La tasa ascenderá a S/. 5.00 por mes.
            <h3>¿El precio del peaje aumenta por usar el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            No. El cobro será según la tarifa de la estación de peaje.
            <h3>¿Qué es la tasa de recarga?</h3>
            Es el monto que el cliente deberá pagar cada vez que realice una recarga en su cuenta <i class=italic>e-pass</i>. Esta tasa se descontará según el importe que realice.
            <!--
            <table id="tasa-recarga">
             <tbody>
               <tr>
                 <th > PROMO Verano TAG + Recarga </th>
                 <th class="th-azul" > Precio Regular del TAG </th>
                 <th > Precio PROMO Verano TAG </th>
                 <th class="th-azul" > Monto de Recarga </th>
                 <th class="th-azul" > Tasa de Recarga Pre-Pago </th>
                 <th class="th-azul" > Saldo para uso </th>
               </tr>
               <tr>
                 <td > S/. 50.00 </td>
                 <td > S/. 20.00 </td>
                 <td > S/. 15.00 </td>
                 <td > S/. 35.00 </td>
                 <td > S/. 2.00 </td>
                 <td  > S/. 33.00 </td>
               </tr>
               <tr>
                 <td > S/. 80.00 </td>
                 <td > S/. 20.00 </td>
                 <td > S/. 15.00 </td>
                 <td > S/. 65.00 </td>
                 <td > S/. 3.50 </td>
                 <td > S/. 61.50 </td>
               </tr>
               <tr>
                 <td > S/. 105.00 </td>
                 <td > S/. 20.00 </td>
                 <td > S/. 15.00 </td>
                 <td > S/. 90.00 </td>
                 <td > S/. 4.50 </td>
                 <td > S/. 85.50 </td>
               </tr>
               <tr>
                 <td > S/. 150.00 </td>
                 <td > S/. 20.00 </td>
                 <td > S/. 10.00 </td>
                 <td > S/. 140.00 </td>
                 <td > S/. 6.50 </td>
                 <td > S/. 133.50 </td>
               </tr>
               <tr>
                 <td > S/. 200.00 </td>
                 <td > S/. 20.00 </td>
                 <td > S/. 10.00 </td>
                 <td > S/. 190.00 </td>
                 <td > S/. 7.50 </td>
                 <td > S/. 182.50 </td>
               </tr>
               <tr>
                 <td > S/. 250.00 </td>
                 <td > S/. 20.00 </td>
                 <td > S/. 10.00 </td>
                 <td > S/. 240.00 </td>
                 <td > S/. 9.00 </td>
                 <td > S/. 231.00 </td>
               </tr>
             </tbody>
           </table>-->
            
        </div>
    </div>

    <div class="line"></div>

    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Adquisión y Recargas <br>
                del <spam class="epas-line"><span><i class=italic>e-pass</i></span></spam>
            </h2>
        </div>
        <div class="col-md-7">
            <h3>¿Dónde puedo adquirir el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            Las personas pueden adquirir su <spam class="epas-line"><i class=italic>e-pass</i></spam> a través de www.epass.pe <a href="#" data-target="#modal_afiliate" data-toggle="modal"> (Hacer Click Aquí)</a>, en los Centros <span><spam class="epas-line"><i class=italic>e-pass</i></spam> (Km 21,5 de la Carretera Panamericana Sur (sentido sur)) o en los puntos de ventas autorizados.
            <h3>¿Dónde puedo recargar el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            Además de los puntos de venta, los clientes también pueden realizar sus recargas a través de la página web www.e-pass.pe.
        </div>
    </div>

    <div class="line"></div>

    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Garantías, Deterioro, Suspensión, Pérdidas o Robos <br>
                del <span><i class=italic>e-pass</i></span>

            </h2>
        </div>
        <div class="col-md-7">
            <h3>¿<spam class="epas-line"><i class=italic>e-pass</i></spam> cuenta con garantía?</h3>
            Sí, y tiene la duración de un año (12 meses)
            <h3>¿Qué tengo que hacer si me pierde o roban mi TAG?</h3>
            Deberá comunicarse a la Central de Atención al Usuario: 0800-45045 o 249-7222 para bloquear su TAG.
            <h3>¿Qué hago si se me malogra o tengo algún problema con mi TAG (dispositivo electrónico)?</h3>
            Tiene que llamar a la Central de Atención al Usuario: 0800-45045 o 249-7222 y explicar su problema. En caso siga sin funcionar, tendrá que acercarse al Centro Playa, ubicado en el Km 21,5 de la Carretera Panamericana Sur (sentido sur) en los siguientes horarios de atención:
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    De lunes a sábado: De 8:30 a.m. a 5:00 p.m
                </div>
            </div>
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    Domingos de 8:30 a.m. a 3:00 p.m.
                </div>
            </div>
            <h3>¿Cuánto durará el período de suspensión del TAG?</h3>
            El período de duración de suspensión será de 2 meses, transcurridos éstos, el TAG volverá a activarse.
        </div>
    </div>
    <div class="line"></div>

    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Consulta de Saldos y Reembolsos de Saldos
            </h2>
        </div>
        <div class="col-md-7">
            <h3>¿Dónde puede consultar los datos y el saldo de mi cuenta <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            El cliente <spam class="epas-line"><i class=italic>e-pass</i></spam> que tiene una cuenta debe ingresar a www.e-pass.pe y darle click a Inicio de Sesión. <a href="#" data-toggle="modal" data-target="#loginModal">(Hacer Click Aquí)</a>.
            <h3>¿Cómo solicitar a <spam class="epas-line"><i class=italic>e-pass</i></spam> el reembolso de su saldo?</h3>
            El cliente deberá acercarse, de forma presencial, a los Centros de Atención al Cliente <spam class="epas-line"><i class=italic>e-pass</i></spam>, portando su Documento Nacional de Identidad (DNI) para suscribir una constancia de reembolso y pagar la tasa administrativa ascendente a S/. 10.00.
        </div>
    </div>

    <div class="line"></div>

    <div class="row v-center">
        <div class="col-md-5">
            <h2>Uso y Registro de Usuarios TAG</h2>
        </div>
        <div class="col-md-7">
            <h3>¿Cómo puede registrarse un cliente en una cuenta <spam class="epas-line"><i class=italic>e-pass</i></spam> si compró su TAG y no dejó sus datos personales?</h3>
            El cliente que no esté registrado no podrá revisar sus saldos ni sus movimientos. Para registrarse, tiene que ingresar a www.e-pass.pe y darle click a Inicio de Sesión e ingresar su TAG o número de Placa y luego ir a la sección "Recarga Directa" donde se muestra la opción de Registro<a data-toggle="modal" data-target="#loginModal" class="click_achi"> (Hacer Click Aquí)</a>.
            <h3>¿Se puede utilizar el TAG en otro vehículo que no esté registrado en el sistema <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h3>
            No. Debe quedar claro que si es un TAG asociado a un vehículo en el sistema <spam class="epas-line"><i class=italic>e-pass</i></spam>, no se puede utilizar.
        </div>
    </div>


</div> <!-- /container -->