<div id="banner" class="banner-quees">   
    <img class="img-lazy" data-original="<?php echo $this->linkCdn('/img/que_es_epass_origin.jpg') ?>" 
    src="<?php echo $this->linkCdn('/img/que_es_epassx30.jpg') ?>" >
    <div id="box">
        <span class=italic>e-pass</span> es Cómodo, <br> Fácil y Simple.
    </div>
    
</div>

<div class="container">
    <div class="info" >
        <h2>¿Qué es el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
        <div class="info_content">
            El <spam class="epas-line"><i class=italic>e-pass</i></spam> es un medio de pago electrónico que permite el paso por los peajes y, próximamente estacionamientos, de manera más ágil y sin tener efectivo.
        </div>
        <img class="info_img"  src="<?php echo $this->linkCdn('/img/card.png') ?>" >
    </div>

    <div class="line"></div>

    <div class="info" >
        <h2>¿Qué ofrece el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
        <div class="info_content">
            El <spam class="epas-line"><i class=italic>e-pass</i></spam> ofrece un sistema de antenas de tecnología RFID (por sus siglas en inglés Radio Frequency Identification; en español Identificación de Radiofrecuencia), que le permitirá al Cliente pasar por los peajes y estacionamientos con mayor comodidad.
        </div>
        <span class="icon icon_foco info_img"></span>
    </div>

    <div class="line"></div>

    <div class="info" >
        <h2>¿Cómo funciona el <spam class="epas-line"><i class=italic>e-pass</i></spam>?</h2>
        <div class="info_content">
            <div class="pasos">
                <div class="pasos-left">
                    <img class="arrows"  src="<?php echo $this->linkCdn('/img/arrows.png') ?>" >
                    <div class="circle_pasos">
                        Paso <br> 1
                    </div>
                </div>
                <div class=" pasos_text">El vehículo se aproxima a la barrera de ingreso a los peajes, estacionamientos u otros servicios autorizados.</div>
            </div>
            <div class="pasos">
                <div class="pasos-left">
                    <img class="arrows" src="<?php echo $this->linkCdn('/img/arrows.png') ?>" >
                    <div class="circle_pasos ">
                        Paso <br>2
                    </div>
                </div>
                <div class=" pasos_text">Nuestro sistema detecta el TAG instalado en el parabrisas.</div>
            </div>
            <div class="pasos">
                <div class="pasos-left">
                    <img class="arrows" src="<?php echo $this->linkCdn('/img/arrows.png') ?>" >
                    <div class="circle_pasos ">
                        Paso <br>3
                    </div>
                </div>
                <div class=" pasos_text">Se enciende la luz verde del semáforo y la barrera se levanta.</div>
            </div>
            <div class="pasos">
                <div class="pasos-left">
                    <img class="arrows" src="<?php echo $this->linkCdn('/img/arrows.png') ?>" >
                    <div class="circle_pasos ">
                        Paso <br>4
                    </div>
                </div>
                <div class="pasos_text">El vehículo continúa con su recorrido.</div>
            </div>
        </div>
        <img class="info_img top_img"  src="<?php echo $this->linkCdn('/img/tranquera.png') ?>" >
    </div>

</div> <!-- /container -->
