
<?php  $this->headLink()
    ->prependStylesheet($this->linkCdn('/css/general/general.css'))
    ->prependStylesheet($this->linkCdn('/css/reclamaciones/reclamaciones.css'))
?>
<div class="TituloAsep">Términes y Condiciones</div>
<div class="contenedor-formulario contenedor-terminos-y-condiciones">
	<p>
	Las recargas estarán activas en un plazo máximo de DOCE (12) horas desde realizada el pago, salvo excepciones indicadas en los Canales de Atención.
	</p>
	<br/>
	<p>
		El cliente establecerá si se le entrega el TAG en su domicilio o si lo retira en alguno de los Centros <i class=italic>e-pass</i>. Desde ese momento, el cliente podrá hacer uso del servicio <i class=italic>e-pass</i>. Junto con la entrega del TAG, se le emitirá su comprobante de pago.
	</p>
	<br/>
	<p>
		El TAG instalado en los vehículos podrá ser identificado por <spam class="epas-line"><i class=italic>e-pass</i></spam>, siempre que el Cliente respete los límites de velocidad indicados en las vías respectivas y establecimientos. La circulación a una velocidad que exceda el límite de velocidad indicado en las vías puede impedir la lectura electrónica del TAG y la activación del alza de la barrera de seguridad.
	</p>
	<br/>
	<p>
		Cada una de las transacciones verificadas y registradas por <i class=italic>e-pass</i>, implicará el cobro de la tarifa de peaje o del servicio autorizado, a ser debitado del saldo en la Cuenta <i class=italic>e-pass</i>. En el caso de los planes Familia, todos los TAGs asignados a una misma Cuenta <i class=italic>e-pass</i> compartirán el saldo y las transacciones de todos ellos serán debitados de dicha Cuenta.
	</p>
	<br/>
	<p>
		Cada una de las transacciones verificadas y registradas por <i class=italic>e-pass</i>, implicará el cobro de la tarifa de peaje o del servicio autorizado, a ser debitado del saldo en la Cuenta <i class=italic>e-pass</i>. En el caso de los planes Familia, todos los TAGs asignados a una misma Cuenta <i class=italic>e-pass</i> compartirán el saldo y las transacciones de todos ellos serán debitados de dicha Cuenta.
	</p>
	<br/>
	<p>
		El Cliente podrá consultar el saldo de su Cuenta <i class=italic>e-pass</i>, accediendo a la misma a través del portal web www.epass.pe, ingresando el código de cliente y su clave secreta. Para ello, se requiere que previamente el Cliente haya registrado sus datos y cada uno de los vehículos que desee afiliar a través de los Canales de Atención, teniendo en cuenta que cada vehículo será asociado exclusivamente a un TAG.
	</p>
	<br/>
	<p>
		El Cliente podrá hacer uso del saldo recargado en su Cuenta <i class=italic>e-pass</i> por el plazo de un (1) año desde la fecha de la última recarga. Transcurrido dicho periodo, en caso el Cliente no registre transacciones o recargas se cargará a su cuenta una tasa de mantenimiento mensual a partir del décimo tercer mes hasta que alcance el saldo. En ningún caso <i class=italic>e-pass</i> reembolsará el importe abonado por el Cliente en dicha cuenta.
	</p>
	<br/>
	<p>
		El funcionamiento del TAG se encuentra garantizado por el plazo de un (1) año. De presentar fallas, se podrá solicitar la revisión e instalación de un TAG nuevo, dependiendo del diagnóstico. <i class=italic>e-pass</i> no es responsable por las fallas o el deterioro, por causas tales como el uso inadecuado, manipulación, remoción o intento de remoción, entre otros afines.
	</p>
	<br/>
	<p>
		Si el cliente solicitara el reembolso de su saldo, <i class=italic>e-pass</i> cobrará una tasa administrativa que será descontada del saldo que será devuelto al Cliente. <i class=italic>e-pass</i> hará efectiva la devolución del saldo al Cliente en los lugares y condiciones que se encuentran publicados en los Canales de Atención.
	</p>
</div>