 <?php  $this->headLink()
             ->prependStylesheet($this->linkCdn('/css/afiliate/afiliate.css'))
 ?> 
 <?php  $this->headScript()                                    
            ->prependFile($this->linkCdn('/js/afiliate/afiliate.js')); 
?>
        
<div class="contenidoAfiliate">
	<div class="titulo">Afiliación</div>
	<p class="letraAfiliate">
		Para obtener nuestro servicio, sólo tiene que completar el siguiente formulario. Una vez que termine el proceso de afiliación, en un plazo no mayor de 72 horas recibirá su e-pass.
	</p>
	<div class="contenedorComponenteCuadroFlecha">
		<!--************** publicidad epassFlecha **************//-->
		<div class="ContenedorCuadroFlecha">
		  <div class="titulo-epassFlecha">Paquete Seleccionado</div>
		  <div class="contenedorPubli">
		    <div class="titulo-Naranja">Plan Individual</div>
		    <div class="flechaConCss"><i class="fa fa-long-arrow-right"></i></div>
		    <div class="titulo-Naranja">Paquete de 50 mil</div>
		  </div>
		</div>
		<!--************** publicidad epassFlecha **************//-->
	</div>
	<div class="contenedorComponenteFormularioEpass">
		<!--************** formulario ePass **************//-->
		<div class="contenedorFormularioEpass">
		  <div class="subContenedorFormularioEpass"><span class="spanEncima">Datos Personales</span>
		    <div class="contenedorInputsEpass row">
		      <div class="form-inline">
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-4">Nombre de Titular :</label>
		          <input id="nombre" type="text" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
		        </div>
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="apellidos" class="spanEpass col-xs-12 col-sm-12 col-md-4">Apellidos del Titular :</label>
		          <input id="apellidos" type="text" placeholder="Ingrese apellidos completos" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
		        </div>
		      </div>
		      <div class="form-inline">
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Tipo de Documento :</label>
		          <select id="docunento" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
		            <option>seleccione</option>
		            <option>DNI</option>
		            <option>RUC</option>
		          </select>
		        </div>
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Nro Documento :</label>
		          <input id="nro_documento" type="text" placeholder="Ingrese numero documento" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
		        </div>
		      </div>
		      <div class="form-inline">
		        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
		          <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Correo :</label>
		          <input id="correo" placeholder="Ingrese correo" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-10 selectpicker"/>
		        </div>
		      </div>
		      <div class="form-inline">
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="contrasenia" class="spanEpass col-xs-12 col-sm-12 col-md-4">Contraseña :</label>
		          <input id="contrasenia" type="text" placeholder="Ingrese contraseña segura" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
		        </div>
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="confirmar_contrasenia" class="spanEpass col-xs-12 col-sm-12 col-md-4">Confirmar Contraseña :</label>
		          <input id="confirmar_contrasenia" type="text" placeholder="Repita contraseña" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
		        </div>
		      </div>
		    </div>
		  </div>
		  <div class="subContenedorFormularioEpass top3em"><span class="spanEncima">Datos del Vehículo</span>
		    <div class="contenedorInputsEpass row">         
		      <div class="form-inline">
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Marca :</label>
		          <select id="docunento" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
		            <option>seleccione</option>
		            <option>DNI</option>
		            <option>RUC</option>
		          </select>
		        </div>
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Modelo :</label>
		          <select id="docunento" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
		            <option>seleccione</option>
		            <option>DNI</option>
		            <option>RUC</option>
		          </select>
		        </div>
		      </div>
		      <div class="form-inline">
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="contrasenia" class="spanEpass col-xs-12 col-sm-12 col-md-4">Placa :</label>
		          <input id="contrasenia" type="text" placeholder="Ingrese contraseña segura" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
		        </div>
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Tipo de Vehículo :</label>
		          <select id="docunento" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
		            <option>seleccione</option>
		            <option>DNI</option>
		            <option>RUC</option>
		          </select>
		        </div>
		      </div>
		    </div>
		  </div>
		  <div class="subContenedorFormularioEpass top3em"><span class="spanEncima">Forma de Entrega</span>
		    <div class="contenedorInputsEpass row">                     
		      <div class="form-inline">
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <input id="contrasenia" name="puedes_cambiarme_si_quieres" value="venta" type="radio" placeholder="Ingrese contraseña segura" class="imputEpass radioEnvioRetiro"/>
		          <label for="contrasenia" class="spanEpass">Retiro en punto de Venta                 </label>
		        </div>
		        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
		          <input id="contrasenia" name="puedes_cambiarme_si_quieres" value="domicilio" type="radio" placeholder="Ingrese contraseña segura" class="imputEpass radioEnvioRetiro"/>
		          <label for="contrasenia" class="spanEpass">Envio a Domicilio</label>
		        </div>
		      </div>
		    </div>
		  </div>
		  <div class="form-venta">
			  	
		  </div>
		  <div class="form-domicilio top3em">
		  		<div class="subContenedorFormularioEpass"><span class="spanEncima">Dirección</span>
			    <div class="contenedorInputsEpass row">
			      <div class="form-inline">
			        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
			          <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Departamento:</label>
			          <select id="docunento" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
			            <option>seleccione</option>
			            <option>DNI</option>
			            <option>RUC</option>
			          </select>
			        </div>
			        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
			          <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Provincia :</label>
			          <select id="docunento" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
			            <option>seleccione</option>
			            <option>DNI</option>
			            <option>RUC</option>
			          </select>
			        </div>
			      </div>
			      <div class="form-inline">
			        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
			          <label for="docunento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Distrito :</label>
			          <select id="docunento" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-8 selectpicker">
			            <option>seleccione</option>
			            <option>DNI</option>
			            <option>RUC</option>
			          </select>
			        </div>
			        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
			          <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Calle/ Av/ Jr :</label>
			          <input id="nro_documento" type="text" placeholder="Ingrese Calle/ Av/ Jr:" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
			        </div>
			      </div>
			      
			      <div class="form-inline">
			        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
			          <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Número :</label>
			          <input id="nro_documento" type="text" placeholder="Ingrese número:" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
			        </div>
			        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
			          <label for="nro_documento" class="spanEpass col-xs-12 col-sm-12 col-md-4">Dpto/ Int :</label>
			          <input id="nro_documento" type="text" placeholder="Ingrese Dpto. Int:" class="imputEpass col-xs-12 col-sm-12 col-md-8"/>
			        </div>
			      </div>
			      <div class="form-inline">
			        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
			          <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Urbanización :</label>
			          <input id="correo" placeholder="Ingrese Urbanización" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-10 selectpicker"/>
			        </div>
			      </div>
			      <div class="form-inline">
			        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
			          <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Referencia :</label>
			          <textarea id="correo" placeholder="Ingrese Urbanización" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-10 selectpicker"></textarea>
			        </div>
			      </div>
			    </div>
			  </div>
		  </div>
		  <div class="subContenedorFormularioEpass cont_check">       
		    <div class="contenedorInputsEpass row">                     
		      <div class="form-inline">
		        <div class="camp_checkbox col-xs-12 col-sm-6 col-md-6">
		          <div>
		            <input type="checkbox" class="inline-block"/><span class="inline-block span_check"><span class="inline-block marg">Acepto los &nbsp;</span><a href="#">términos y condiciones</a><span>&nbsp; del servicio</span></span>
		          </div>
		          <div>
		            <input type="checkbox" class="inline-block"/><span class="inline-block marg span_check">Quiero recibir novedades de e-pass</span>
		          </div>
		        </div>
		      </div>
		      <div class="btn_siguientePaso col-xs-12 col-sm-6 col-md-6"><a >Siguiente Paso</a></div>
		    </div>
		  </div>
		</div>
		<!--************** formulario ePass **************//-->
	</div>
</div>