<div id="banner">
    <img  src="<?php echo $this->linkCdn('/img/banner_beneficios.jpg') ?>" >
    <div id="box">
            Permite realizar el pago<br>
            de sus peajes, <br>
            estacionamientos y otros <br>
            servicios autorizados de<br>
            manera más cómoda.
    </div>
    <div class="barra_verder" ></div>
</div>

<div class="container">
    <div id="adquirir_beneficios" class="info" >
        <h2>¿Cuáles son los Beneficios al adquirir el e-pass?</h2>
        <div class="info_content">
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Los clientes ya no necesitarán de efectivo para el pago del peaje, estacionamientos y otros servicios autorizados.</div>
            </div>
            <div class="item"><div class="icon item_icon"></div>
                <div class="item_text">Paso por una vía exclusiva sin detenerse para hacer el pago</div>
            </div>
            <div class="item"><div class="icon item_icon"></div>
                <div class="item_text">Las recargas se podrán realizar por cargo automático.</div>
            </div>
        </div>
        <img class="info_img"  src="<?php echo $this->linkCdn('/img/peaje.png') ?>" >       
        <span class="icon icon_car"></span>
    </div>
    
    <div class="line"></div>
    
    <div class="info" >
        <h2>¿Qué otros Beneficios extras brinda el e-pass?</h2>
        <div class="info_content">
            ¿Cuáles son los Beneficios al adquirir el e-pass?
            Brinda al cliente el paso fácil, cómodo y simple por los peajes de Rutas de Lima, concesión que tiene a su cargo la operación y mantenimiento de la carretera Panamericana Norte, desde el Óvalo Habich hasta el Intercambio de Ancón, y de la carretera Panamericana Sur, desde el Trébol de Javier Prado hasta el Puente Pucusana.
        </div>
        <span class="icon icon_foco info_img"></span>        
    </div>  
    
    <div class="line"></div>
    
    <div class="info" >
        <h2>¿Dónde puedo hacer uso de los Beneficios del e-pass?</h2>
        <div class="info_content">
            El cliente podrá hacer uso de los Beneficios de e-pass en los siguientes peajes:
            <div class="row">
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Arica<br>
                        (Panamericana Sur Km. 35)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Huaylas<br>
                        (Panamericana Sur Km. 18.4)</div>
                </div>                
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Chillón<br>
                        (Panamericana Norte Km. 25)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Punta Negra<br>
                        (Panamericana Norte Km. 45.1) </div>
                </div>                
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Conchán<br>
                        (Panamericana Sur Km. 25.5)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Villa<br>
                        (Panamericana Sur Km. 19.8)</div>
                </div>             
            </div>
        </div>
        <img class="info_img"  src="<?php echo $this->linkCdn('/img/peaje.png') ?>" > 
    </div>    

</div> <!-- /container -->
