<div id="banner">
    <img  src="<?php echo $this->linkCdn('/img/banner_queesepass.jpg') ?>" >
    <div id="box">
        El TAG está diseñado para<br>
        que pueda ser utilizado en <br>
        todo tipo de vehículos, ya<br>
        sean livianos, pesados y <br>
        públicos.
    </div>
    <div class="barra_verder" ></div>
</div>

<div class="container">
    
    <div class="info" >
        <h2>¿Cuáles son los pasos para poner el TAG en su vehículo?</h2>
        <div class="info_content">
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Es muy sencillo. El TAG (dispositivo electrónico) se coloca debajo del espejo retrovisor.</div>
            </div>
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Siga sólo estos tres pasos para poner el TAG en su vehículo:</div>
            </div> 
            <img  src="<?php echo $this->linkCdn('/img/como_1.png') ?>" >
        </div>
    </div>   

    <div class="line"></div>
    
    <div class="info" >
        <h2>Recuerde que ...</h2>
        <div class="info_content">
            <img  src="<?php echo $this->linkCdn('/img/como_2.png') ?>" >
        </div>
    </div>   
   

</div> <!-- /container -->
