 <?php  $this->headLink()
             ->prependStylesheet($this->linkCdn('/css/afiliate/afiliate.css'))
 ?>
<?php  $this->headScript()                                    
            ->prependFile($this->linkCdn('/js/contactanos/contactanos.js')); ?> 

<form id="form_contactanos">        
	<div class="contenidoContactanos">
		<div class="titulo-contactanos">Contáctanos</div>
			<div class="">
				<div class="">
				    <div class="contenedorInputsEpass row">
					    <div class="form-inline">
					        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
					          <label for="nombre" class="spanEpass col-xs-12 col-sm-6 col-md-4">Nombre :</label>
					          <div class="col-xs-12 col-sm-12 col-md-8">
					          	<input id="nombre" name="nombre" type="text" placeholder="Ingrese nombre completo" class="imputEpass col-xs-12 col-sm-12 col-md-12 required" minlength="3" />
					          </div>
					        </div>
					        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
					          <label for="apellidos" class="spanEpass col-xs-12 col-sm-12 col-md-4">Apellidos :</label>
					          <div class="col-xs-12 col-sm-12 col-md-8">
					               <input id="apellidos" name="apellidos" type="text" placeholder="Ingrese apellidos completos" class="imputEpass col-xs-12 col-sm-12 col-md-12 required" minlength="3"/>
					           </div>
					        </div>
					    </div>
					    <div class="form-inline">
					        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
					          	<label for="telefono_contacto" class="center-label spanEpass col-xs-12 col-sm-12 col-md-4">Teléfono :</label>
					          	<div class="col-xs-12 col-sm-12 col-md-8">
					           		<input id="telefono_contacto"  name="telefono_contacto" type="text" placeholder="Ingrese teléfono" class="imputEpass col-xs-12 col-sm-12 col-md-12 required digits" />
					           	</div>
					        </div>
					        <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
					          	<label for="telefono_adicional" class="center-label spanEpass col-xs-12 col-sm-12 col-md-4">Teléfono Adicional:</label>
					          	<div class="col-xs-12 col-sm-12 col-md-8">
					           		<input id="telefono_adicional" name="telefono_adicional" type="text" placeholder="Ingrese teléfono" class="imputEpass col-xs-12 col-sm-12 col-md-12 required digits" />
					           	</div>
					        </div>
					    </div>
					    <div class="form-inline">
					        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
					          <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-2">Correo :</label>
					          <div class="col-xs-12 col-sm-12 col-md-10">
					          		<input id="correo" name="correo" placeholder="Ingrese correo" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-12 required email" minlength="3" />
					          </div>
					        </div>
					    </div>
					    <div class="form-inline">
					        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
					          	<label for="asunto" class="spanEpass col-xs-12 col-sm-12 col-md-4">Asunto :</label>
					          	<div class="col-xs-12 col-sm-12 col-md-12">
					          		<input id="asunto" name="asunto" type="text" placeholder="Ingrese asunto" class="imputEpass col-xs-12 col-sm-12 col-md-12 required" minlength="4"/>
					          	</div>
					        </div>
					        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
					          	<label for="mensaje" class="spanEpass col-xs-12 col-sm-12 col-md-4">Mensaje :</label>
					          	<div class="col-xs-12 col-sm-12 col-md-12">
					          		<textarea id="mensaje" name="mensaje" type="text" placeholder="Ingrese mensaje" class="textarea-contactanos required col-xs-12 col-sm-12 col-md-12"  minlength="10"></textarea>
					          	</div>
					        </div>
					    </div>
					    <div class="form-inline">
					        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
					          	<label for="asunto" class="spanEpass">
					          		<input type="checkbox" name="no_robot" class="required" />
					          		No soy un robot
					          	</label>
					        </div>
					    </div>
				    </div>
				</div>
				<div>
					<button type="submit" class="btn btn-enviar">Enviar</button>
				</div>
			</div>  
	</div>
</form>