<div id="banner">
    <img  src="<?php echo $this->linkCdn('/img/banner_donde.jpg') ?>" >
    <div id="box">
        Las personas o empresas<br>
        interesadas pueden adquirir<br>
        <a href="#">aquí</a> su e-pass vía web.
    </div>
    <div class="barra_verder" ></div>
</div>

<div class="container">
    <div class="info" >
        <h2>¿Dónde puedo adquirir el e-pass?</h2>
        <div class="info_content">
            El usuario podrá adquirir el e-pass en los siguientes canales de atención:
            <div class="row">
                <div class="item col-md-4"><span class="icon item_icon"></span>
                    <div class="item_text">Vía Web</div>
                </div>
                <div class="item col-md-4"><span class="icon item_icon"></span>
                    <div class="item_text">Vía Telefónica</div>
                </div>
                <div class="item col-md-4"><span class="icon item_icon"></span>
                    <div class="item_text">Centros de Ventas</div>
                </div>          
            </div>
        </div>
        <span class="icon icon_row info_img"></span> 
    </div>   
    
    <div class="line"></div>
    
    <div class="info" >
        <h2>¿Cuáles son los centros de venta autorizados de e-pass?</h2>
        <div class="info_content">
            Los centros de ventas autorizados de e-pass están ubicados en:
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Km 18 de la Carretera Panamericana Sur, sentido sur (antes del ingreso a Huaylas)</div>
            </div>
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Km 21,5 de la Carretera Panamericana Sur, sentido sur (al costado del Touring y Automóvil Club del Perú)</div>
            </div>         
        </div>
    </div>   
    
    <div class="line"></div>
    
    <div class="info" >
        <h2>¿Cuáles son los Horarios de Atención en los Centros de Venta Autorizados del e-pass?</h2>
        <div class="info_content">
            Los horarios de atención de los centros de ventas autorizados de e-pass son:
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Lunes a Domingo, 8:30 a.m. a 6:30 p.m.</div>
            </div>
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">Cualquier información adicional no dude en comunicarse a la Central de Atención al Cliente: <br>
0800-45045 o 2497222</div>
            </div>         
        </div>
        <img class="info_img people_group" src="<?php echo $this->linkCdn('/img/group.png') ?>" >
    </div> 
    
    <div class="line"></div>
    
    <div class="info" >
        <h2>¿Cuáles son los Medios de Pago viables para la adquisión del e-pass?</h2>
        <div class="info_content">
            El e-pass trabaja con los siguientes Medios de Pago:
            <div class="medios_pago">
                <img src="<?php echo $this->linkCdn('/img/visa.jpg') ?>" >
                <img src="<?php echo $this->linkCdn('/img/mastercard.jpg') ?>" >
                <img src="<?php echo $this->linkCdn('/img/american_express.jpg') ?>" >
                <img src="<?php echo $this->linkCdn('/img/diners_club.jpg') ?>" >
            </div>
            <p>Para Recargas: Web, Puntos de Venta, Vía BCP y Agentes BCP</p>
            <p>Cargos recurrente: Tarjetas de Crédito y Cuenta BCP (*)</p>
            <p class="info_adicional">(*) Los Clientes también tendrán la posibilidad de hacerlo bajo la modalidad de Cargos Recurrentes </p>
            
        </div>
        <img class="info_img card_send" src="<?php echo $this->linkCdn('/img/card_send.png') ?>" >
    </div>      

</div> <!-- /container -->
