<?php   $this->headLink()
    ->prependStylesheet($this->linkCdn('/css/general/general.css'))
    ->prependStylesheet($this->linkCdn('/css/empresa/empresa.css'))
?>
<?php  $this->headScript()
    ->prependFile($this->linkCdn('/js/general/general.js'))
    ->prependFile($this->linkCdn('/js/empresa/empresa.js'));
    //->prependFile($this->linkCdn('/js/empresa/empresa.js'));
?>

<!--**************Conoce Nuestro Plan Individual **************-->
<div class="titleEnPersona" id="href_planes_prepago">
    ¿Qué paquete desas Recargar?
</div>
<div class="col-md-12">
        <div class="col-xs-12 col-sm-6 col-md-3 margencito">
            <!--************** paquete ePass **************//-->
            <div class="paqueteEpass">
                <div class="prepago-red">Prepago</div>
                <div class="paqueteEpass-Titulo"><span>Paquete 1</span></div>
                <div class="contenedorContenido">
                    <div class="paqueteEpass-Contenido">
                        <div class="paqueteEpass-Contenido-Precio "><span class="soles">S/.</span>
                            <div class="precio"><span>160.00 </span><span> *</span></div>
                        </div>
                        <div class="paqueteEpass-Contenido-Recarga"><span>Sólo Recarga</span></div>
                        <div class="paqueteEpass-Contenido-bloque1  maspadding"><span>Saldo para uso</span><span class="saldo-monto">S/. 133.50</span></div>
                       
                        <div class="paqueteEpass-Contenido-bloque3 sinDashed maspadding"><span>Tasa Recarga</span><span class="saldo-monto"> S/.6.50</span></div>
                        <div class="paqueteEpass-Contenido-VerMas"><span class="">AfÃ&shy;liate</span></div>
                    </div>
                </div>
            </div>
            <!--************** paquete ePass **************//-->
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3 margencito">
            <!--************** paquete ePass **************//-->
            <div class="paqueteEpass">
                <div class="prepago-red">Prepago</div>
                <div class="paqueteEpass-Titulo"><span>Paquete 2</span></div>
                <div class="contenedorContenido">
                    <div class="paqueteEpass-Contenido">
                        <div class="paqueteEpass-Contenido-Precio "><span class="soles">S/.</span>
                            <div class="precio"><span>210.00 </span><span> *</span></div>
                        </div>
                        <div class="paqueteEpass-Contenido-Recarga"><span>Sólo Recarga</span></div>
                        <div class="paqueteEpass-Contenido-bloque1  maspadding"><span>Saldo para uso</span><span class="saldo-monto">S/. 182.50</span></div>
                       
                        <div class="paqueteEpass-Contenido-bloque3 sinDashed maspadding"><span>Tasa Recarga</span><span class="saldo-monto"> S/.7.50</span></div>
                        <div class="paqueteEpass-Contenido-VerMas"><span class="">AfÃ&shy;liate</span></div>
                    </div>
                </div>
            </div>
            <!--************** paquete ePass **************//-->
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3 margencito">
            <!--************** paquete ePass **************//-->
            <div class="paqueteEpass">
                <div class="prepago-red">Prepago</div>
                <div class="paqueteEpass-Titulo"><span>Paquete 3</span></div>
                <div class="contenedorContenido">
                    <div class="paqueteEpass-Contenido">
                        <div class="paqueteEpass-Contenido-Precio "><span class="soles">S/.</span>
                            <div class="precio"><span>260.00 </span><span> *</span></div>
                        </div>
                        <div class="paqueteEpass-Contenido-Recarga"><span>Sólo Recarga</span></div>
                        <div class="paqueteEpass-Contenido-bloque1  maspadding"><span>Saldo para uso</span><span class="saldo-monto">S/. 231.00</span></div>
                       
                        <div class="paqueteEpass-Contenido-bloque3 sinDashed maspadding"><span>Tasa Recarga</span><span class="saldo-monto"> S/.9.00</span></div>
                        <div class="paqueteEpass-Contenido-VerMas"><span class="">AfÃ&shy;liate</span></div>
                    </div>
                </div>
            </div>
            <!--************** paquete ePass **************//-->
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3 margencito">
            <!--************** paquete ePassMas **************//-->            
            <div class="paqueteEpass">
                <div class="paqueteEpass-TituloPlomo"><span>Paquete</span></div>
                <div class="contenedorContenidoPlomo">
                    <div class="paqueteEpass-Contenido">
                        <div class="paqueteEpass-Contenido-PrecioPlomo">
                            <div class="precioPlomo"><span>Post-Pago</span></div>
                        </div>
                        <div class="paqueteEpass-Contenido-RecargaPlomo"><span>Consulta </span><a  data-toggle="modal" data-target="#modal_post_pago_recarga_consulta">aquí </a><span>
                       nuestros Paquetes Post-Pago Empresas que tenemos para ti.</span></div>
                        <div class="paqueteEpass-Contenido-VerMasPlomo"><span data-toggle="modal" data-target="#modal_post_pago_recarga_consulta">Consultar</span></div>
                    </div>
                </div>
            </div>
            <!--************** paquete ePassMas **************//-->
        </div>
    </div>


</div>
<div class="texto-asterisco">
    (*) El costo del TAG por vehículo afiliado al contrato será adicionado al monto del paquete elegido y el mismo será cobrado al concluir su afiliación
</div>
<div class="row col-md-12 publicidadEpass" >
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="publicidadEpass-Texto">Si ya cuentas con el TAG de e-pass, ¡Qué esperas!</div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 center">
        <div class="publicidadEpass-Button">
        <a href="#">
            <span>Afíliate Aquí</span>
            <i class="fa fa-angle-right"></i>
        </a>
        </div>
    </div>
</div>
