<?php   $this->headLink()
             ->prependStylesheet($this->linkCdn('/css/general/general.css'))
             ->prependStylesheet($this->linkCdn('/css/persona/persona.css'))
 ?>
 <?php  $this->headScript()            
            ->prependFile($this->linkCdn('/js/general/general.js'))
            ->prependFile($this->linkCdn('/js/persona/persona.js'))
        ; ?>
        
        

 <!--************** posit ePass **************//-->
<div class="posit-Epass-Container">
  <div class="posit-Epass-Consulta-Oculta">
    <div><i class="fa fa-hand-o-down"></i></div>
      <div class="posit-Epass-Consulta-Oculta-background">
            <div class="letras-90deg">S</div>
            <div class="letras-90deg">A</div>
            <div class="letras-90deg">T</div>
            <div class="letras-90deg">L</div>
            <div class="letras-90deg">U</div>
            <div class="letras-90deg">S</div>
            <div class="letras-90deg">N</div>
            <div class="letras-90deg">O</div>
            <div class="letras-90deg">C</div>
      </div>                    
  	</div>
	<div class="posit-Epass">
	  <div class="posit-Epass-Consulta"> 
	    <div class="posit-Epass-Titulo"> Consultas</div>
	    <a href="#" class="infoConsultasHref">
	        <div class="posit-Epass-MisSaldos">
	          <div class="posit-Epass-titulo">Mis Saldos</div>
	          <div class="posit-Epass-MisSaldos-Contenido"><span class="ePass-flecha"><i class="fa fa-angle-right"></i></span><span><i class="fa fa-hand-o-up"></i></span><span class="ePass-flecha"><i class="fa fa-angle-left"></i></span></div>
            </div>
        </a>
        <a href="#" class="infoConsultasHref">
            <div class="posit-Epass-MisSaldos">
              <div class="posit-Epass-titulo">Mis Datos</div>
              <div class="posit-Epass-MisSaldos-Contenido"><span class="ePass-flecha"><i class="fa fa-angle-right"></i></span><span><i class="fa fa-credit-card"></i></span><span class="ePass-flecha"> <i class="fa fa-angle-left"></i></span></div>
            </div>
        </a>
        <a href="#" class="infoConsultasHref">
            <div class="posit-Epass-MisSaldos">
              <div class="posit-Epass-titulo">Recargar</div>
              <div class="posit-Epass-MisSaldos-Contenido"><span class="ePass-flecha"><i class="fa fa-angle-right"></i></span><span><i class="fa fa-refresh"></i></span><span class="ePass-flecha"> <i class="fa fa-angle-left">      </i></span></div>
            </div>
      	</a>
      <div class="posit-Epass-Footer">Cerrar</div>
    </div>
  </div>
</div>
<!--**************fin posit ePass **************//-->


<!--**************Conoce Nuestro Plan Individual **************-->
<div class="titleEnPersona">
	Conoce nuestros Paquetes del Plan Individual
</div>
<div class="col-md-12 sinPaddingRight">
	<div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePass **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-Titulo"><span>Paquete 1</span></div>
		  <div class="contenedorContenido">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-Precio"><span class="soles">S/.</span>
		        <div class="precio"><span>50.00 </span><span> *</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-Recarga"><span>Recarga + TAG</span></div>
		      <div class="paqueteEpass-Contenido-bloque1"><span>Saldo para uso</span><span class="saldo-monto">S/. 33.0</span></div>
		      <div class="paqueteEpass-Contenido-bloque2">
		        <div class="relative">
		          <div>Costo TAG</div>
		          <div class="saldo-monto tachado"> 
		            <strike>(S/.20.00) </strike>
		          </div>
		        </div>
		        <div class="relative">
		          <div class="pad">Promo Verano</div>
		          <div class="saldo-monto top0 specialPrice">S/.15.00				</div>
		        </div>
		      </div>
		      <div class="paqueteEpass-Contenido-bloque3 sinDashed"><span>Tasa Recarga</span><span class="saldo-monto"> S/.2.00</span></div>
		      <div class="paqueteEpass-Contenido-VerMas"><span>Afíliate</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePass **************//-->
    </div>
   	<div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePass **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-Titulo"><span>Paquete 1</span></div>
		  <div class="contenedorContenido">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-Precio"><span class="soles">S/.</span>
		        <div class="precio"><span>50.00 </span><span> *</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-Recarga"><span>Recarga + TAG</span></div>
		      <div class="paqueteEpass-Contenido-bloque1"><span>Saldo para uso</span><span class="saldo-monto">S/. 33.0</span></div>
		      <div class="paqueteEpass-Contenido-bloque2">
		        <div class="relative">
		          <div>Costo TAG</div>
		          <div class="saldo-monto tachado"> 
		            <strike>(S/.20.00) </strike>
		          </div>
		        </div>
		        <div class="relative">
		          <div class="pad">Promo Verano</div>
		          <div class="saldo-monto top0 specialPrice">S/.15.00				</div>
		        </div>
		      </div>
		      <div class="paqueteEpass-Contenido-bloque3 sinDashed"><span>Tasa Recarga</span><span class="saldo-monto"> S/.2.00</span></div>
		      <div class="paqueteEpass-Contenido-VerMas"><span>Afíliate</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePass **************//-->
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePass **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-Titulo"><span>Paquete 1</span></div>
		  <div class="contenedorContenido">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-Precio"><span class="soles">S/.</span>
		        <div class="precio"><span>50.00 </span><span> *</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-Recarga"><span>Recarga + TAG</span></div>
		      <div class="paqueteEpass-Contenido-bloque1"><span>Saldo para uso</span><span class="saldo-monto">S/. 33.0</span></div>
		      <div class="paqueteEpass-Contenido-bloque2">
		        <div class="relative">
		          <div>Costo TAG</div>
		          <div class="saldo-monto tachado"> 
		            <strike>(S/.20.00) </strike>
		          </div>
		        </div>
		        <div class="relative">
		          <div class="pad">Promo Verano</div>
		          <div class="saldo-monto top0 specialPrice">S/.15.00				</div>
		        </div>
		      </div>
		      <div class="paqueteEpass-Contenido-bloque3 sinDashed"><span>Tasa Recarga</span><span class="saldo-monto"> S/.2.00</span></div>
		      <div class="paqueteEpass-Contenido-VerMas"><span>Afíliate</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePass **************//-->
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePassMas **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-TituloPlomo"><span>Más</span></div>
		  <div class="contenedorContenidoPlomo">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-PrecioPlomo">				
		        <div class="precioPlomo"><span>Paquetes</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-RecargaPlomo"><span>Conoza </span><a href="#">aquí </a><span>
		           más paquetes que tenemos para ti en
		          nuestro plan individual.</span></div>
		      <div class="paqueteEpass-Contenido-VerMasPlomo"><span>Consultar</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePassMas **************//-->
    </div>
</div>
<div class="dashedLine"></div>
<div class="titleEnPersona">
	Conoce nuestros Paquetes del Plan Compartido
</div>
<div class="col-md-12 sinPaddingRight">
	<div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePass **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-Titulo bgceleste"><span>Paquete 1</span></div>
		  <div class="contenedorContenido borderCeleste">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-Precio bgceleste"><span class="soles">S/.</span>
		        <div class="precio"><span>50.00 </span><span> *</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-Recarga"><span class="colorceleste">Recarga + TAG</span></div>
		      <div class="paqueteEpass-Contenido-bloque1 dashedCeleste"><span>Saldo para uso</span><span class="saldo-monto">S/. 33.0</span></div>
		      <div class="paqueteEpass-Contenido-bloque2 dashedCeleste">
		        <div class="relative">
		          <div>Costo TAG</div>
		          <div class="saldo-monto tachado"> 
		            <strike>(S/.20.00) </strike>
		          </div>
		        </div>
		        <div class="relative">
		          <div class="pad">Promo Verano</div>
		          <div class="saldo-monto top0 specialPrice">S/.15.00				</div>
		        </div>
		      </div>
		      <div class="paqueteEpass-Contenido-bloque3 sinDashed"><span >Tasa Recarga</span><span class="saldo-monto"> S/.2.00</span></div>
		      <div class="paqueteEpass-Contenido-VerMas bgCelesteTransparent"><span class="bgceleste">Afíliate</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePass **************//-->
    </div>
   	<div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePass **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-Titulo bgceleste"><span>Paquete 1</span></div>
		  <div class="contenedorContenido borderCeleste">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-Precio bgceleste"><span class="soles">S/.</span>
		        <div class="precio"><span>50.00 </span><span> *</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-Recarga"><span class="colorceleste">Recarga + TAG</span></div>
		      <div class="paqueteEpass-Contenido-bloque1 dashedCeleste"><span>Saldo para uso</span><span class="saldo-monto">S/. 33.0</span></div>
		      <div class="paqueteEpass-Contenido-bloque2 dashedCeleste">
		        <div class="relative">
		          <div>Costo TAG</div>
		          <div class="saldo-monto tachado"> 
		            <strike>(S/.20.00) </strike>
		          </div>
		        </div>
		        <div class="relative">
		          <div class="pad">Promo Verano</div>
		          <div class="saldo-monto top0 specialPrice">S/.15.00				</div>
		        </div>
		      </div>
		      <div class="paqueteEpass-Contenido-bloque3 sinDashed"><span>Tasa Recarga</span><span class="saldo-monto"> S/.2.00</span></div>
		      <div class="paqueteEpass-Contenido-VerMas bgCelesteTransparent"><span class="bgceleste">Afíliate</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePass **************//-->
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePass **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-Titulo bgceleste"><span>Paquete 1</span></div>
		  <div class="contenedorContenido borderCeleste">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-Precio bgceleste"><span class="soles">S/.</span>
		        <div class="precio"><span>50.00 </span><span> *</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-Recarga"><span class="colorceleste">Recarga + TAG</span></div>
		      <div class="paqueteEpass-Contenido-bloque1 dashedCeleste"><span>Saldo para uso</span><span class="saldo-monto">S/. 33.0</span></div>
		      <div class="paqueteEpass-Contenido-bloque2 dashedCeleste">
		        <div class="relative">
		          <div>Costo TAG</div>
		          <div class="saldo-monto tachado"> 
		            <strike>(S/.20.00) </strike>
		          </div>
		        </div>
		        <div class="relative">
		          <div class="pad">Promo Verano</div>
		          <div class="saldo-monto top0 specialPrice">S/.15.00				</div>
		        </div>
		      </div>
		      <div class="paqueteEpass-Contenido-bloque3 sinDashed"><span>Tasa Recarga</span><span class="saldo-monto"> S/.2.00</span></div>
		      <div class="paqueteEpass-Contenido-VerMas bgCelesteTransparent"><span class="bgceleste">Afíliate</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePass **************//-->
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3 margencito">
        <!--************** paquete ePassMas **************//-->
		<div class="paqueteEpass">
		  <div class="paqueteEpass-TituloPlomo"><span>Más</span></div>
		  <div class="contenedorContenidoPlomo">
		    <div class="paqueteEpass-Contenido">
		      <div class="paqueteEpass-Contenido-PrecioPlomo">				
		        <div class="precioPlomo"><span>Paquetes</span></div>
		      </div>
		      <div class="paqueteEpass-Contenido-RecargaPlomo"><span>Conoza </span><a href="#">aquí </a><span>
		           más paquetes que tenemos para ti en
		          nuestro plan familiar.</span></div>
		      <div class="paqueteEpass-Contenido-VerMasPlomo"><span>Consultar</span></div>
		    </div>
		  </div>
		</div>
		<!--************** paquete ePassMas **************//-->
    </div>
</div>
</div>
<div class="texto-asterisco">
	(*) El costo del TAG por vehículo afiliado al contrato será adicionado al monto del paquete elegido y el mismo será cobrado al concluir su afiliación
</div>
<div class="col-md-12 publicidadEpass" >
	<div class="col-xs-12 col-sm-12 col-md-6">
		<div class="publicidadEpass-Texto">Si ya cuentas con el TAG de e-pass, ¡Qué esperas!</div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-6 center">
		<div class="publicidadEpass-Button"><a href="#"><span>Recarga Aquí</span><i class="fa fa-angle-right"></i></a></div>
	</div>
</div>
