<div id="banner">
    <img  src="<?php echo $this->linkCdn('/img/banner_preguntas.jpg') ?>" >
    <div id="box">
            Aquí podrás encontrar las<br>
            respuestas a las preguntas<br>
            más frecuentes.
    </div>
    <div class="barra_verder" ></div>
</div>

<div class="container preguntas_frecuentes">
    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Características  y Beneficios<br>
                del <span>e-pass</span>
            </h2>
        </div>
        <div class="col-md-7">

            <h3>¿Qué es el e-pass?</h3>
            Es un medio de pago electrónico que permite el paso por los peajes y estacionamientos de manera más ágil y sin tener efectivo.
            <h3>¿Dónde puedo hacer uso de los Beneficios del e-pass?</h3>
            Usted podrá hacer uso de los Beneficios de e-pass en los siguientes peajes:
            <div class="row">
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Arica<br>
                        (Panamericana Sur Km. 35)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Huaylas<br>
                        (Panamericana Sur Km. 18.4)</div>
                </div>                
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Chillón<br>
                        (Panamericana Norte Km. 25)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Punta Negra<br>
                        (Panamericana Norte Km. 45.1) </div>
                </div>                
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Conchán<br>
                        (Panamericana Sur Km. 25.5)</div>
                </div>
                <div class="item col-md-6"><span class="icon item_icon"></span>
                    <div class="item_text">Peaje Villa<br>
                        (Panamericana Sur Km. 19.8)</div>
                </div>            
            </div>
        </div>
    </div>
    <div class="line"></div>
    
    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Colocación y Funcionamiento de <br>
                mi <span>e-pass</span>
            </h2>
        </div>
        <div class="col-md-7">

            <h3>¿Cómo coloco el TAG de e-pass en mi vehículo?</h3>
            En el folleto informativo que usted recibió cuando adquirió el TAG se encuentran las instrucciones para colocar el TAG en su vehículo. Asimismo, también podrá encontrar el paso a paso en www.e-pass.com/como-colocar-tu-epass
            <h3>¿Cómo funciona mi e-pass?</h3>
            Si usted ya cuenta con su TAG colocado en su vehículo, deberá seguir el siguiente procedimiento:
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    Su vehículo deberá aproximarse a la barrera de ingreso al peaje, estacionamiento u otro servicio autorizado. 
                </div>
            </div> 
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    Nuestro sistema detectará su TAG que se encuentra colocado en el parabrisas de su vehículo.                     
                </div>
            </div> 
            <div class="item"><span class="icon item_icon"></span>
                <div class="item_text">
                    Se encenderá la luz verde del semáforo y la barrera se levantará para que pase con su vehículo.                     
                </div>
            </div>             

        </div>
    </div>
    <div class="line"></div>

    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Costos y  Vigencia <br>
                del <span>e-pass</span>
            </h2>
        </div>
        <div class="col-md-7">

            <h3>¿Cuál es el precio del TAG e-pass?</h3>
            El precio es de S/.20. En caso sufra un daño por la manipulación del cliente, la reposición tiene un valor de S/.20.
            <h3>¿El monto recargado tiene fecha de vencimiento?</h3>
            No tiene fecha de vencimiento. Sin embargo, a partir del año de realizada la recarga se cobrará una tasa de mantenimiento.
            <h3>¿Qué es la tasa de mantenimiento?</h3>
            La tasa de mantenimiento se activará en caso el Cliente e-pass no registre transacciones o recargas al finalizar 12 meses completos. La tasa ascenderá a S/. 5.00 por mes.
            <h3>¿El precio del peaje aumenta por usar el e-pass?</h3>
            No. El cobro será según la tarifa de la estación de peaje.
            <h3>¿Qué es la tasa de recarga?</h3>
            La tasa de recarga es el monto que el Cliente deberá pagar cada vez que realice una Recarga en su Cuenta e-pass y que será descontada de la misma.

        </div>
    </div>
    
    <div class="line"></div>
    
    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Adquisión y Recargas <br>
                del <span>e-pass</span>
            </h2>
        </div>
        <div class="col-md-7">
            <h3>¿Dónde puedo adquirir el e-pass?</h3>
            Las personas o empresas interesadas pueden adquirir su e-pass a través de la página web (www.epass.pe), en los Centros e-pass (Km 21,5 de la Carretera Panamericana Sur (sentido sur) o en el Km 18 (sentido sur)) o en los puntos de ventas autorizados.
            <h3>¿Dónde puedo recargar el e-pass?</h3>
            El usuario podrá recargar el e-pass en los siguientes canales de atención:
            <div class="row">
                <div class="col-md-6">
                    <div class="item"><span class="icon item_icon"></span>
                        <div class="item_text">
                            Vía Web
                        </div>
                    </div>  
                </div>
                <div class="col-md-6">
                    <div class="item"><span class="icon item_icon"></span>
                        <div class="item_text">
                            Centros de Venta
                        </div>
                    </div> 
                </div>
            </div>
            <h3>¿Cuál es el monto mínimo que debe tener mi cuenta e-pass para que se haga efectiva la carga automática?</h3>
            La recarga automática se hará efectiva cuando el monto mínimo sea de S/. 15.00.
        </div>
    </div>  
    
    <div class="line"></div>  
    
    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Garantías, Deterioro, Suspensión, Pérdidas o Robos <br>
                del <span>e-pass</span>

            </h2>
        </div>
        <div class="col-md-7">
            <h3>¿e-pass cuenta con garantía?</h3>
            Sí, y tiene la duración de un año (12 meses) 
            <h3>¿Qué tengo que hacer si me pierde o roban mi TAG?</h3>
            Deberá comunicarse a la Central de Atención al Usuario: 0800-45045 o 249-7222 para bloquear su TAG.
            <h3>¿Qué hago si se me malogra o tengo algún problema con mi TAG (dispositivo electrónico)?</h3>
            Tiene que llamar a la Central de Atención al Usuario: 0800-45045 o 249-7222 y explicar su problema. En caso siga sin funcionar, tendrá que acercarse al Centro Playa, ubicado en el Km 21,5 de la Carretera Panamericana Sur (sentido sur) en los siguientes horarios de atención
                <div class="item"><span class="icon item_icon"></span>
                    <div class="item_text">
                        De lunes a sábado: De 8:30 a.m. a 5:00 p.m
                    </div>
                </div> 
                <div class="item"><span class="icon item_icon"></span>
                    <div class="item_text">
                        Domingos de 8:30 a.m. a 3:00 p.m. 
                    </div>
                </div> 
            <h3>¿Cuánto durará el período de suspensión del TAG?</h3>
            El período de duración de suspensión será de 2 meses, transcurridos éstos, el TAG volverá a activarse.
        </div>
    </div>   
    <div class="line"></div>  
    
    <div class="row v-center">
        <div class="col-md-5">
            <h2>
                Consulta de Saldos y Reembolsos de Saldos                
            </h2>
        </div>
        <div class="col-md-7">
            <h3>¿Dónde puede consultar los datos y el saldo de mi cuenta e-pass?</h3>
            Si usted ya está afiliado a e-pass entonces deberá ingresar con su correo electrónico a nuestra página Web (www.epass.pe).
            <h3>¿Cómo solicitar a e-pass el reembolso de mi saldo?</h3>
            Deberá acercarse de forma presencial a los Centros de Atención al Cliente e-pass, portando su Documento Nacional de Identidad (DNI), para suscribir una constancia de reembolso y pagar la tasa administrativa ascendente a S/. 10.00.
        </div>
    </div>    

    <div class="line"></div>  
    
    <div class="row v-center">
        <div class="col-md-5">
            <h2>Uso y Registro de Usuarios TAG</h2>
        </div>
        <div class="col-md-7">
            <h3>¿Cómo puedo obtener una cuenta e-pass si sólo he comprado mi TAG y no he dejado mis datos personales?</h3>
            Si usted no está  afiliado no podrá revisar sus saldos ni sus movimientos. Para registrarse, tiene que ingresar a www.e-pass.pe y darle click a Registrar.
            <h3>¿Se puede utilizar el TAG en otro vehículo que no esté registrado en el sistema e-pass?</h3> 
            Sí, y tiene la duración de un año (12 meses). 
        </div>
    </div>        
   

</div> <!-- /container -->
