<div id="banner">
    <img  src="<?php echo $this->linkCdn('/img/banner_queesepass.jpg') ?>" >
    <div id="box">
        e-pass es Cómodo, <br> Fácil y Simple.
    </div>
    <div class="barra_verder" ></div>
</div>

<div class="container">
    <div class="info" >
        <h2>¿Qué es el e-pass?</h2>
        <div class="info_content">
            El e-pass es un medio de pago electrónico que permite el paso por los peajes y estacionamientos de manera más ágil y sin tener efectivo.
        </div>
        <img class="info_img"  src="<?php echo $this->linkCdn('/img/card.png') ?>" >
    </div>
    
    <div class="line"></div>
    
    <div class="info" >
        <h2>¿Qué ofrece el e-pass?</h2>
        <div class="info_content">
            El e-pass ofrece un sistema de antenas de tecnología RFID (por sus siglas en inglés Radio Frequency Identification; en español Identificación de Radiofrecuencia), que le permitirá al Cliente pasar por los peajes y estacionamientos con mayor comodidad.
        </div>
        <span class="icon icon_foco info_img"></span>        
    </div>  
    
    <div class="line"></div>
    
    <div class="info" >
        <h2>¿Cómo funciona el e-pass?</h2>
        <div class="info_content">
            <div class="pasos row">
                <div class="col-md-3">
                    <img class="arrows"  src="<?php echo $this->linkCdn('/img/arrows.png') ?>" >
                    <div class="circle_pasos">
                        Paso <br> 1
                    </div>
                </div>
                <div class="col-md-9 pasos_text">El vehículo se aproxima a la barrera de ingreso a los peajes, estacionamientos u otros servicios autorizados.</div>
            </div>
            <div class="pasos row">
                <div class="col-md-3">
                    <img class="arrows" src="<?php echo $this->linkCdn('/img/arrows.png') ?>" >
                    <div class="circle_pasos ">
                        Paso <br>2
                    </div>
                </div>
                <div class="col-md-9 pasos_text">Nuestro sistema detecta el TAG instalado en el parabrisas.</div>
            </div>
        </div>
        <img class="info_img"  src="<?php echo $this->linkCdn('/img/tranquera.png') ?>" >
    </div>

</div> <!-- /container -->
