<ul id="enlace-tab-cuenta" class="nav nav-tabs" role="tablist">
	<li id="tab-resumen" role="presentation" class="active">
		<a id="resumen_dashboard" href="#resumen" aria-controls="home" role="tab" data-toggle="tab">Resumen</a>
	</li>
	<li id="tab-datos" role="presentation">
		<a id="tab-mis-datos" href="#misdatos" aria-controls="profile" role="tab" data-toggle="tab">Mis Datos</a>
		</li>
	<li id="tab-recarga-directa" role="presentation">
		<a id="tab-recarga-directa" href="#recargadirecta" aria-controls="profile" role="tab" data-toggle="tab">Recarga Directa</a>
	</li>
</ul>
