<footer>
    <div class="footer_barra"></div>
    <div id="atencion_cliente">
        <img src="<?php echo $this->linkCdn('/img/atencion_cliente.jpg') ?>" >
        <div id="atencion_cliente_text">
            Central de Atención al Cliente<br>
            <i class="fa fa-phone"></i> 0800-45045 o 249-7222 <br>
            <i class="fa fa-envelope"></i> atencionalcliente@epass.pe
        </div>
    </div>
    <div  class="zkte-spad content row v-center-lg v-center-md text-xs-center ">
        <div class="footer_item col-md-3 col-sm-6">
            <div class="col-md-12 sinPadding">
                <img class="img_logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass"> 
                   <br>
                   <br>
                   © Todos los derechos reservados, 2016.
            </div>
        </div>
        <div class="footer_item col-md-3 col-sm-6">
             <div class="row footer-separate">
                <div class="col-xs-2 col-sm-2 col-md-2 align-right">
                    <i class="fa fa-building fa-lg"></i> 
                </div>
                <div class="col-xs-10 col-sm-10 col-md-10 align-text">
                   
                    Panamericana Sur km 19.65 <div>(sentido sur)</div>
                </div> 
            </div>
            <div class="row">
                <div class="col-xs-2 col-sm-2 col-md-2 align-right">
                    <i class="fa fa-envelope-o fa-lg"></i> 
                </div>
                <div class="col-xs-10 col-sm-10 col-md-10 align-text">
                    atencionalcliente@epass.pe
                </div> 
            </div>
        </div>
        <div class="footer_item col-md-3 col-sm-6">
             <div class="row footer-separate">
                <div class="col-xs-2 col-sm-2 col-md-2 align-right">
                    <i class="fa fa-headphones fa-lg"></i>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-10 align-text">
                    <a href="<?php echo $this->url('contacto') ?>"> Contáctanos</a>
                </div> 
            </div>
            <div class="row">
                <div class="col-xs-2 col-sm-2 col-md-2 align-right">
                    <i class="fa fa-phone fa-lg"></i> 
                </div>
                <div class="col-xs-10 col-sm-10 col-md-10 align-text">
                    0800-45045 o 249-7222
                </div> 
            </div>
        </div>
        <div class="footer_item col-md-3 col-sm-6">
            <div class="col-md-12">
                <img class="footer-img" src="<?php echo $this->linkCdn('/img/libro_reclamacion.svg') ?>" >
                <a class="libro_reclamacion_text" id="libro_reclamacion" target="_blank"  href="<?php echo $this->url('reclamaciones') ?>">
 
                        Libro de 
                        Reclamaciones
                </a>
            </div>            
        </div>
    </div>

</footer>
