<header>
    
    <nav id="menu_principal" class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed btn-primary-mov" data-toggle="collapse" data-target="#navbar-collapse-principal" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="logo" class="navbar-brand" href="<?php echo '/' ?>">
                    <img src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
                </a>
            </div>

            <?php echo $this->navigation('top_menu_navigation')
                ->menu()
                ->setPartial('renders/menu_top')
                ->render();
            ?>
        </div><!-- /.container-fluid -->
    </nav>

    <nav id="menu_secundario" class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-secundario" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <?php echo $this->navigation('bottom_menu_navigation')
                ->menu()
                ->setPartial('renders/menu_bottom')
                ->render();
            ?>

        </div><!-- /.container-fluid -->
    </nav>


</header>
<input id="vista-actual" type="hidden" value=""/>
