<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body">
       <div class="row v-center">
           
            <div id="login" class="col-md-6">
                <h2>Inicia tu Sesión</h2>
                <h4>Ingresa tu correo y contraseña con el que te afiliaste por web.</h4>
                <form id="form-login" action="login" method="POST">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" ><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                            <input type="text" class="form-control required email" placeholder="Correo" name="username" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
                            <input type="password" class="form-control required" placeholder=" Contraseña" name="password" >
                        </div>                  
                    </div>
                    <button type="submit" class="btn btn-default">Ingresar</button>
                </form>
                <a href="#">Olvidé mi contraseña</a>
                <br>
                <label>
                    <input type="checkbox"> Recordar mi contraseña
                </label>
            </div>
           
           
            <div id="recarga" class="col-md-6">
               <h2>Recarga Directa</h2>
               <h4>Para recargar debe ingresar su número de tag o placa</h4>
               <form id="form-recarga" action="" method="POST">
                    <div class="form-group">
                        <div class="row tipos">
                            <div class="col-md-6">
                                <input type="radio" class="required"  name="type" value="tag"> Número de Tag
                            </div>
                            <div class="col-md-6 ">
                                <input type="radio" class="required"  name="type" value="placa"> Número de Placa
                            </div>
                        </div>
                    </div>                  
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" ><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span></span>
                            <input type="text" class="form-control required digits" placeholder=" Los 8 digitos de su Tag o  su número de placa"  name="nroType">
                        </div>                  
                    </div>
                    <button type="submit" class="btn btn-default">Recargar</button>
                </form>
               <br>
               <a href="#">¿Quieres ver tus saldos?. Actualiza tus datos y obtén tu usuario Web.</a>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>