<!-- Modal -->
<div class="modal fade" id="modal_recargadirecta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body">           

                <div class="alert alert-danger alert-dismissible hidden" role="alert">                  
                  <div class="alert-message"> </div>
                </div>
               <h2>Recarga Directa</h2>
               <h4>Para recargar debe ingresar su número de tag o placa</h4>
               <form id="form-recarga" class="form-recarga-directa" action="/login/recarga" method="POST">
                    <div class="form-group">
                        <div class="row tipos">
                            <div class="col-md-6">
                                <input id="radio_label_tag_id" type="radio" class="required radio-tag-change"  name="type" value="tag"> 
                                <label for="radio_label_tag_id" class="cursorPointer">Número de Tag</label>
                            </div>
                            <div class="col-md-6 ">
                                <input id="radio_label_placa_id" type="radio" class="required radio-placa-change"  name="type" value="placa"> 
                                <label for="radio_label_placa_id" class="cursorPointer">Número de Placa</label>  
                            </div>
                        </div>
                    </div>                  
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" ><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span></span>
                            <input onKeyUp="this.value=this.value.toUpperCase();" disabled="disabled" type="text" class="form-control required txt-tag-o-placa" minlength="6" placeholder=""  name="nroType" >
                        </div>                  
                    </div>
                    <button type="submit" class="btn btn-default recarga-tag-show-proload" value="btn_only_recarga">Recargar</button>
                </form>
      </div>
    </div>
  </div>
</div>
