<div class="modal fade confirmacion_popup" id="modal_mensaje_recuperar_contra" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo-confirmacion" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body orange-confirmacion">
            <div class="recuperar-title">
              Recuperación de contraseña
            </div>
            <div class="mensaje-confirmacion">
                <?php echo $this->message?>           
            </div>
          
            <?php  if(!empty($this->email)){ ?>
                <div class="alert alert-danger alert-dismissible hidden" role="alert">
                  <div class="alert-message"> </div>
                </div>    
                <form id="form-only-recoverpassword" action="/login/recuperar" method="POST">
                    <input type="hidden" name="username" value="<?php echo $this->email?>">
                    <div class="row padding-btn">
                        <button type="submit" class=" btn btn-default"><?php echo $this->button?></button>
                    </div>
                </form>
                <div class="alert alert-success hidden">
                    <div class="alert-message"></div>
                    <a type="button" href="/" class="btn btn-default">Continuar</a>
                </div>
            <?php } else { ?>
                <div class="row padding-btn">
                    <button type="submit" class=" btn btn-default" data-dismiss="modal" data-toggle="modal" data-target="#modal_only_login"><?php echo $this->button?></button>
                </div>
            <?php }?>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#modal_mensaje_recuperar_contra').modal('show')
</script>