

<!-- Modal -->
<div class="modal fade" id="modal_recarga" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-afiliate" role="document">
    <div class="modal-content bg-transparent">
      <div class="modal-header">        
        <h4 class="modal-title modal_afiliate_title" id="myModalLabel">
          Elige tu Recarga
          <button type="button" class="close close_afiliate" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </h4>
      </div>
      <div class="modal-body">
          <div class="col-md-12">
          <div class="col-xs-12  col-md-1">
          </div>
          <div class="col-xs-12 col-sm-6 col-md-5">
              <!--************** gota ePass **************//-->
              <div class="gota-epas gota-epas-modal link_recarga_personas">
                <div class="gota-epas-titulo"><span>Personas</span></div>
                <div class="gota-epas-img">
                  <div class="gota-epas-btn"><a href="<?= $this->basePath() ?>/recarga-personas"><span>Ver Planes</span><i class="fa fa-angle-right"></i></a></div>
                </div>
              </div>
              <!--************** gota ePass **************//-->
          </div>
          <div class="col-xs-12 col-sm-6 col-md-5 segunda-gota">
              <!--************** gota ePass **************//-->
              <div class="gota-epas bg-celeste gota-epas-modal link_recarga_empresas">
                <div class="gota-epas-titulo"><span>Empresas</span></div>
                <div class="gota-epas-img gota-epas-img-transarent-celeste">
                  <div class="gota-epas-btn"><a href="<?= $this->basePath() ?>/recarga-empresas"><span>Ver Planes</span><i class="fa fa-angle-right"></i></a></div>
                </div>
              </div>
              <!--************** gota ePass **************//-->
          </div>
          <div class="col-xs-12  col-md-1">
          </div>
             
          
          <!-- FLECHITAS -->
      </div>
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>