<div class="modal fade confirmacion_popup" id="check_email_messages" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo-confirmacion" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body lightblue-confirmacion">
            <div class="mensaje-confirmacion">
                <?php echo $this->message ?>
            </div>
            <div class="row padding-btn">
                <button type="submit" class=" btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#check_email_messages').modal('show')
</script>
