<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body">
       <div class="row v-center-md v-center-lg">
           
            <div id="login" class="col-md-6">
                
                <div class="alert alert-danger alert-dismissible hidden" role="alert">                  
                  <div class="alert-message"> </div>
                </div>

                <h2>Inicia tu Sesión</h2>
                <h4>Ingresa tu correo y contraseña con el que te afiliaste por web.</h4>
                <form class="form-login" action="/login" method="POST">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" ><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                            <input id="correo-user-zkt" type="text" class="form-control required email inputColor" placeholder="Correo" name="username" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
                            <input type="password" class="form-control required inputColor" placeholder=" Contraseña" name="password" >
                        </div>                  
                    </div>
                    <button value="modal_preload_sesion_recarga" type="submit" class="btn btn-default recarga-tag-show-proload" id="btn-ingresar">Ingresar</button>
                    <label class="recordar-contra">
                        <input type="checkbox" id="remember" > Recordar mi contraseña
                    </label>
                </form>
                
                <br>
                <a href="#" data-toggle="modal" data-target="#recoverPasswordModal" id="forget-pw-id">Olvidé mi contraseña</a>
            </div>
           
           
            <div id="recarga" class="col-md-6">
                <div class="alert alert-danger alert-dismissible hidden" role="alert">                  
                  <div class="alert-message"> </div>
                </div>
               <h2>Recarga Directa</h2>
               <h4>Para recargar debe ingresar su número de tag o placa</h4>
                <form id="form-recarga" class="form-recarga-directa" action="/login/recarga" method="POST">
                    <div class="form-group">
                        <div class="row tipos">
                            <div class="col-md-6">
                                <input id="readio-tag" type="radio" class="radio-tag-change required "  name="type" value="tag"> 
                                <label for="readio-tag" class="cursorPointer">Número de Tag</label>
                            </div>
                            <div class="col-md-6 ">
                                <input  id="radio-placa" type="radio" class="required radio-placa-change"  name="type" value="placa"> 
                                <label for="radio-placa" class="cursorPointer">Número de Placa</label>
                            </div>
                        </div>
                    </div>                  
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" ><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span></span>
                            <input onKeyUp="this.value=this.value.toUpperCase();" disabled type="text" class="txt-tag-o-placa form-control required inputColor" minlength="6" placeholder=""  name="nroType">
                        </div>                  
                    </div>
                    <button type="submit"  class="recarga-tag-show-proload btn btn-default" value="btn-recarga-sesion">Recargar</button>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="recoverPasswordModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog tick-289" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body">
            <div class="alert alert-danger alert-dismissible hidden" role="alert">
                  <div class="alert-message"> </div>
            </div>
            <h2 id="title-recover-pw">Recuperación de Contraseña</h2>
            <h5 id="mensaje-seguiradad-contra" class="algn-left">Por favor ingresa tu correo  con el que te registraste.</h5>
            <form id="form-recoverpassword" action="/login/recuperar" method="POST">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon" ><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                        <input id="correo-recupera-pw" type="text" class="form-control required email inputColor" placeholder="Correo" name="username" >
                    </div>
                </div>
                 <button type="submit" class="btn btn-default">Continuar</button>
             </form>
            <div class="alert alert-success hidden">
                <div class="alert-message"></div>
                <a type="button" href="/" class="btn btn-default">Ir al Inicio</a>
            </div>

      </div>
    </div>
  </div>
</div>
