
<!-- Modal -->
<div class="modal fade" id="modal_post_pago_consulta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal_post_pago_consulta_descripcion">
      <div class="modal-header modal_post_pago_consulta_header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title txtalgn-center" id="myModalLabel">
          <img class="logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body modal_post_pago_consulta_descripcion">
        <div class="modal-body_post_pago_text">
          Para adquirir nuestros paquetes post-pago por favor comunicate vía telefónica a los siguientes números.
        </div>
        <div class="modal_phone">
          <i class="fa fa-phone"></i> 0800-45045 o 249-7222
        </div>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>