
<!-- Modal -->
<div class="modal fade" id="modal_post_pago_recarga_consulta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal_post_pago_consulta_descripcion">
      <div class="modal-header modal_post_pago_consulta_header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title txtalgn-center" id="myModalLabel">
          <img class="logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body modal_post_pago_consulta_descripcion">
        <div class="modal-body_post_pago_text">
          <div>
            Si deseas adquirir el plan post-pago empresas, podrás solicitarlo en los siguientes canales de atención:
          </div>
          <div>
            Teléfono: 249-7222
          </div>
          <div>
            E-mail: atencionalcliente@epass.pe
          </div>
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-default btn-lg btn-cerrar-modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>