<div class="modal fade confirmacion_popup" id="check_email_caducidad_cuenta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo-confirmacion" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body lightblue-confirmacion">
            <div class="hidden">
                <input type="hidden" class="email_check" name="email" value="<?php echo $this->email?>"/>
                <input type="hidden" class="iduser_check" name="iduser" value="<?php echo $this->iduser?>"/>
            </div>
            <div class="mensaje-confirmacion">
                El proceso de activación de cuenta ha caducado. Deberás realizar nuevamente el proceso solicitándolo <a class="generate-new-check-email aqui" href="#">Aquí</a>
            </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade confirmacion_popup" id="agradecimiento_cuenta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
            <img class="logo-confirmacion" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
        </h4>
      </div>
      <div class="modal-body lightblue-confirmacion">
            <div class="mensaje-confirmacion">
              Se te ha enviado un mail a tu correo <span id="correo"> <?php echo $this->email?></span> con el enlace para que Actives tu Cuenta de Usuario Web en e-pass.
            </div>
            <div class="row padding-btn">
                <button type="submit" class=" btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#check_email_caducidad_cuenta').modal('show');
</script>
