<div id="modal-parent">
    <div class="modal fade" id="modal_recuperar_contra" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="alert alert-danger alert-dismissible hidden" role="alert">
            <div class="alert-message"> </div>
        </div>  
        <form id="form_recuperar_password" action="change-password" method="POST">
          <div class="modal-content modal_recuperar_contrasenia_descripcion">
          <div class="modal-header modal_post_pago_consulta_header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title txtalgn-center" id="myModalLabel">
              <img class="logo" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
            </h4>
          </div>
          <div class="modal-body modal_recuperar_contrasenia_descripcion">
            <div class="modal-body_post_pago_text">
              <div class="recuperar-title">
                Recuperar Contraseña:
              </div>
              <div class="contenedor-Form-recupcontra ">
                  <div>
                  Nueva Contraseña
                  </div>
                  <div>
                    <input type="password" class="required" name="new_password" id="new_password"/>
                  </div>
                  <div>
                    Repita Contraseña:
                  </div>
                  <div>
                    <input type="password" class="required" name="repeat_password" id="repeat_password" />
                  </div>
                  <div>
                      <input type="hidden" name="email" value="<?php echo $this->email?>"/>
                  </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-default btn-lg btn-cerrar-modal color-orange">Cambiar Contraseña</button>
          </div>
          </div>
        </form>
      </div>
    </div>    

    <div class="modal fade confirmacion_popup" id="recuperar_exito_cambiopassword" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content ">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">
                  <img class="logo-confirmacion" src="<?php echo $this->linkCdn('/img/logo.svg') ?>" alt="Epass">
              </h4>
            </div>
            <div class="modal-body orange-confirmacion">
                  <h4>Proceso Exitoso</h4>
                  <div class="mensaje-confirmacion">
                    Se realizó el cambio de la contraseña de manera exitosa. Por favor inicie sesión para que acceda a su cuenta de usuario web en e-pass. 

                  </div>
                  <div class="row padding-btn">
                      <button type="submit" class=" btn btn-default" data-dismiss="modal" data-toggle="modal" data-target="#modal_only_login" >Iniciar Sesión</button>
                  </div>
            </div>
          </div>
        </div>
    </div>
</div>      

<script type="text/javascript">
  $('#modal_recuperar_contra').modal('show');
</script>
