<div class="modal fade confirmacion_popup" id="error_solicitud_enviada" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-body red-confirmacion">
            <div class="mensaje-confirmacion">
              Hubo un problema al enviar la solicitud, por favor intente nuevamente
            </div>
            <div class="row padding-btn">
                <button type="button" class="btn btn-default" data-dismiss="modal" >Cerrar</button>
            </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade confirmacion_popup" id="solicitud_enviada" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-body lightblue-confirmacion">
            <div class="mensaje-confirmacion">
             Su solicitud ha sido enviada
            </div>
            <div class="row padding-btn">
                <button type="button" class="btn btn-default" data-dismiss="modal" >Cerrar</button>
            </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade confirmacion_popup" id="error_cambiar_cuenta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-body red-confirmacion">
            <div class="mensaje-confirmacion">
              Hubo un problema al cambiar la cuenta, por favor intente nuevamente
            </div>
            <div class="row padding-btn">
                <button type="button" class="btn btn-default" data-dismiss="modal" >Cerrar</button>
            </div>
      </div>
    </div>
  </div>
</div>