<div id="DataTables_Table_0_paginate" class="dataTables_paginate paging_simple_numbers">
    <a id="DataTables_Table_0_previous" tabindex="0" data-dt-idx="0" aria-controls="DataTables_Table_0" class="paginate_button previous disabled">
        <i class="fa fa-step-backward"></i></a>
    <span>
        <a tabindex="0" data-dt-idx="1" aria-controls="DataTables_Table_0" class="paginate_button current">1</a>
        <a tabindex="0" data-dt-idx="2" aria-controls="DataTables_Table_0" class="paginate_button ">2</a>
    </span>
    <a id="DataTables_Table_0_next" tabindex="0" data-dt-idx="3" aria-controls="DataTables_Table_0" class="paginate_button next">
        <i class="fa fa-step-forward"></i>
    </a>
</div>
