<?php  $this->headLink()
			->prependStylesheet($this->linkCdn('/css/administrador/micuenta.css'))
			->prependStylesheet($this->linkCdn('/css/administrador/reportes.css'))
			->prependStylesheet($this->linkCdn('/css/afiliate/afiliate.css'))
			->prependStylesheet($this->linkCdn('/css/general/general.css'))
?>
<div class="container-alert">
			<div class="alert alert-dismissible" role="alert">
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  Para poder ver sus Saldos, Últimas Recargas, Comprobantes de Pago y Cuentas Asociadas deberá activar su cuenta. Esta activación deberá hacerla desde su cuenta de correo que registró al momento de crear su usuario web en <i class="italic">e-pass</i>.
			</div>
	</div>
	<?php echo $this->partial('layout/render/dashboard'); ?>
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="resumen">
			<div class="container-fluid">
				<div class="col-md-9">
					<div class="box-background">
						<div class="item">
							<p class="title-item">Datos Principales <i class="fa fa-user fa-3"></i></p>
						</div>
						<div class="row content-datos">
							<div class="col-md-6 box-datos">
								<table>
									<tr>
										<td><label>Nombre y Apellido: </label></td>
										<td><label>Jhon Smith Miller</label></td>
										
									</tr>
									   <tr>
										<td><label>Tipo de Documento: </label></td>
										<td><label>DNI</label></td>
										
									</tr>
									   <tr>
										<td><label>Nro Documento: </label></td>
										<td><label>7055585589</label></td>
								</table>

							</div>
							<div class="col-md-6 box-datos">
								<table>
									<tr>
										<td><label>Usuario: </label></td>
										<td><label>jsmith171@gmail.com</label></td>
										
									</tr>
									   <tr>
										<td><label>Tipo de Cuenta: </label></td>
										<td><label>Pre-Pago - Individual</label></td>
										
									</tr>
								</table>
							</div>

						</div>
					</div>
					<div class="box-background">
						<div class="item">
							<p class="title-item">Últimas Recargas </p>
						</div>
						<br>
						<div>
							<table class="table table-responsive table-personalizada">
									<thead>
										<tr>
											<th>Fecha de Recarga</th>
											<th>Paquete de Recarga</th>
											<th>Monto de Recarga</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>sample text</td>
											<td>sample text</td>
											<td>sample text</td>
										</tr>
										 <tr>
											<td>sample text</td>
											<td>sample text</td>
											<td>sample text</td>
										</tr>
										<tr>
											<td>sample text</td>
											<td>sample text</td>
											<td>sample text</td>
										</tr>
										<tr>
											<td>sample text</td>
											<td>sample text</td>
											<td>sample text</td>
										</tr>
									</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="misdatos">
			<div class="container-fluid">
				<div class="col-md-9">
					<div class="box-background box-padding">
						<div class="subContenedorFormularioEpass separate">
							<span class="spanEncima">Datos Principales</span>
                        	<div class="row box-padding-extremo">
	                            <div class="form-inline">
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-6">Nombre de Titular:</label>
	                                    <input id="fecha_hasta" type="text" class="imputEpass col-xs-12 col-sm-12 col-md-6 disabled-input" value="Jhon"/>
	                                </div>
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-6">Apellidos Titular:</label>
	                                    <input id="fecha_hasta" type="text" class="imputEpass col-xs-12 col-sm-12 col-md-6 disabled-input" value="Smith"/> 
	                                </div>
	                            </div>
	                            <div class="form-inline">
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-6">Tipo de Documento</label>
	                                    <select id="tipo"  class="imputEpass col-xs-12 col-sm-12 col-md-6 selectpicker disabled-input">
                                        	<option>seleccione</option>
                                        	<option>DNI</option>
                                        	<option>RUC</option>
                                    	</select>
	                                </div>
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-6">Nro Documento:</label>
	                                    <input id="nro_documento" type="text" class="imputEpass col-xs-12 col-sm-12 col-md-6" value="Smith"/> 
	                                </div>
	                            </div>
	                            <div class="form-inline">
							        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
							          <label for="correo" class="spanEpass col-xs-12 col-sm-12 col-md-3">Correo :</label>
							          <input id="correo" placeholder="Ingrese correo" class="slSinMarg imputEpass col-xs-12 col-sm-12 col-md-9 "/>
							        </div>
							    </div>
                        	</div>
                    	</div>
                    	<div class="subContenedorFormularioEpass separate">
							<span class="spanEncima">Dirección</span>
                        	<div class="row box-padding-extremo">
	                            <div class="form-inline">
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-6">Departamento:</label>
	                                     <select id="tipo"  class="selectpicker col-xs-12 col-sm-12 col-md-6 ">
                                        	<option>La Libertad</option>
                                        	<option>Piura</option>
                                        	<option>Lima</option>
                                    	</select>
	                                </div>
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-6">Provincia:</label>
	                                     <select id="tipo"  class="selectpicker col-xs-12 col-sm-12 col-md-6 ">
                                        	<option>Trujillo</option>
                                        	<option>Virú</option>
                                        	<option>Chepén</option>
                                    	</select>
	                                </div>
	                            </div>
	                            <div class="form-inline">
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="nombre" class="spanEpass col-xs-12 col-sm-12 col-md-6">Distrito:</label>
	                                     <select id="tipo"  class="selectpicker col-xs-12 col-sm-12 col-md-6 ">
                                        	<option>Trujillo</option>
                                        	<option>La Esperanza</option>
                                        	<option>El Porvenir</option>
                                    	</select>
	                                </div>
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="calle" class="spanEpass col-xs-12 col-sm-12 col-md-6">Calle/Av/Jr:</label>
	                                    <input id="fecha_hasta" type="text" class="imputEpass col-xs-12 col-sm-12 col-md-6" value="Av. Las Gavidias"/>
	                                </div>
	                            </div>
	                            <div class="form-inline">
	                               	<div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="numero" class="spanEpass col-xs-12 col-sm-12 col-md-6">Numero:</label>
	                                    <input id="numero" type="text" class="imputEpass col-xs-12 col-sm-12 col-md-6" value="325"/>
	                                </div>
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="dpto" class="spanEpass col-xs-12 col-sm-12 col-md-6">Dpto / Int: </label>
	                                    <input id="dpto" type="text" class="imputEpass col-xs-12 col-sm-12 col-md-6" placeholder="Ingrese Dpto. Int."/> 
	                                </div>
	                            </div>
	                            <div class="form-inline">
	                               	<div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="urbanizacion" class="spanEpass col-xs-12 col-sm-12 col-md-6">Urbanización:</label>
	                                    <input id="urbanizacion" type="text" class="imputEpass col-xs-12 col-sm-12 col-md-6" value="325"/>
	                                </div>
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                </div>
	                            </div>
	                            <div class="form-inline">
							        <div class="bloqueInput col-xs-12 col-sm-12 col-md-12 form-group">
							          <label for="referencia" class="spanEpass col-xs-12 col-sm-12 col-md-3">Referencia :</label>
							          <textarea placeholder="Ingrese una referencia" class="col-xs-12 col-sm-12 col-md-9"></textarea>
							        </div>
							    </div>
                        	</div>
                    	</div>
                    	<div class="subContenedorFormularioEpass separate">
							<span class="spanEncima">Contraseña</span>
                        	<div class="row box-padding-extremo">
	                            <div class="form-inline">
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="password" class="spanEpass col-xs-12 col-sm-12 col-md-6">Nueva Clave:</label>
	                                    <input id="password" type="password" class="imputEpass col-xs-12 col-sm-12 col-md-6" />
	                                </div>
	                                <div class="bloqueInput col-xs-12 col-sm-6 col-md-6 form-group">
	                                    <label for="n_clave" class="spanEpass col-xs-12 col-sm-12 col-md-6">Repetir Clave:</label>
	                                    <input id="n_clave" type="password" class="imputEpass col-xs-12 col-sm-12 col-md-6" /> 
	                                </div>
	                            </div>
                        	</div>
                    	</div>
                    	<div class="row">
                    		<div class="col-md-offset-2 col-xs-12 col-sm-12 col-md-8">
                    				<button type="submit" class="btn btn-border"	>Actualizar</button>
                    				<button type="button" class="btn btn-border"	>Cancelar</button>
                    		</div>
                    	</div>
					</div>
				</div>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="recargadirecta">
			<div class="container-fluid">
				<div class="col-md-9">
					<div class="box-background box-padding sinPading">
						<!--
                    	<div class="contenidoAfiliate">
							<div class="titulo">Afiliación</div>
							<p class="letraAfiliate">
								Para obtener nuestro servicio, sólo tiene que completar el siguiente formulario. Una vez que termine el proceso de afiliación, en un plazo no mayor de 72 horas recibirá su e-pass.
							</p>-->
							<div class="contenedorComponenteCuadroFlecha">
								<!--************** publicidad epassFlecha **************//-->
								<div class="ContenedorCuadroFlecha">
								  <div class="titulo-epassFlecha">Paquete Seleccionado</div>
								  <div class="contenedorPubli">
								    <div class="titulo-Naranja">Plan Individual</div>
								    <div class="flechaConCss"><i class="fa fa-long-arrow-right"></i></div>
								    <div class="titulo-Naranja">Paquete de 50 mil</div>
								  </div>
								</div>
								<!--************** publicidad epassFlecha **************//-->
							</div>
							<div class="contenedorComponenteFormularioEpass">
								<!--************** formulario ePass **************//-->
								<div class="contenedorFormularioEpass">
									<div class="subContenedorFormularioEpass cont_check">
									
									<div class="row">
										<div class="col-xs-12 col-sm-12 col-md-12 mrgbottom2em">Seleccione el tipo de Medio Pago</div>
										<div class="row">
											<div class=" col-xs-12 col-sm-6 col-md-3">
											<img class="img_medio_pago" src="/static/img/visa.jpg">
											</div>
											<div class=" col-xs-12 col-sm-6 col-md-3">
												<img class="img_medio_pago" src="/static/img/mastercard.jpg">
											</div>
											<div class=" col-xs-12 col-sm-6 col-md-3">
												<img class="img_medio_pago" src="/static/img/american_express.jpg">
											</div>
											<div class=" col-xs-12 col-sm-6 col-md-3">
												<img class="img_medio_pago" src="/static/img/diners_club.png">
											</div>
											</div>
										<div class="row">
											<div class="col-xs-12 col-sm-6 col-md-3 ">
											</div>					
											<div class="col-xs-12 col-sm-6 col-md-3 ">
											</div>
											<div class="btn_siguientePaso  align-center col-xs-12 col-sm-6 col-md-3 ">
												<a>Paso Anterior</a>
											</div>
											<div class="btn_siguientePaso  align-center col-xs-12 col-sm-6 col-md-3 ">
												<a>Siguiente Paso</a>
											</div>
										</div>
										
									</div>
								  	 
								  </div>
								</div>
								<!--************** formulario ePass **************//-->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
